<?php 
include("timecard_print.css");

?><div class="portlet">
<div class="title">Timecard</div>
<div class="left"><?php echo $Timecard_user->GetUserFullName()?></div>
<div class="right">Period Starting <?php echo $startdate?></div>
<div class="right">Period Ending <?php echo $enddate?></div>
    <Table>
	<tr>
		<th>Time In</th>
		<th>Time Out</th>
		<th>Duration<br/>(minutes)</th>
		<th>Duration<br/>(hours)</th>
		<th>Running<br/> Total<br/>(hours)</th>
	</tr>
<?php 
//now display all the clock in and out entries
$running_total = 0;
foreach($stamps as $row)
{
	?>	
	<tr>
	<td><?php echo $row['clock_in']?></td>
	<td><?php echo $row['clock_out']?></td>
	<td align=right><?php 
		if($row['clock_out'] != "")
		{
		$sec_dif = strtotime($row['clock_out'])-strtotime($row['clock_in']);
		$minute = $sec_dif / 60;
		echo number_format($minute, 2);
		}
	?>
	</td>
	<td align=right><?php 
		if($row['clock_out'] != "")
		{
		$hours =  $minute / 60;
		echo number_format($hours, 2);
		}
	?>
	</td>
	<td align=right><?php 
		if($row['clock_out'] != "")
		{
		$running_total += $hours;
		echo number_format($running_total, 2);
		}
	?>
	</td>
	</tr>
	<?php $edits = $Timecard->getAllEditsToTimecard($row['timecard_id']);
    	if(is_array($edits))
    	{
    		foreach($edits as $edit)
    		{
				?>
				<tr>
				<td><?php echo $edit['newclock_in']?><BR />
				 was
				 <BR /> <?php echo $edit['oldclock_in']?> </td>
				<td><?php echo $edit['newclock_out']?><BR />
				 was<BR />
				  <?php echo $edit['oldclock_out']?> </td>
				<td></td>
				<td></td>
				<td></td>
				<td>EDIT BY <?php echo $edit['username']?></td>
				
				<tr>
				<?php  
				
    		}
    	}
    	unset($edits);

}



?>
	<tr>
		<td></td>
		<td colspan=2 align=right>HOURS WORKED</td>
		<td align=right><?php echo number_format($running_total, 2)?></td>
	</tr>
	<tr>
		<td></td>
		<td colspan=2 align=right>+Meeting/Mod Time</td>
		<td align=right><?php echo @number_format($comp, 2); $running_total += $comp;
	    ?></td>
	</tr>
	<tr>
		<td></td>
		<td colspan=2 align=right>TOTAL REGULAR HOURS:</td>
		<td align=right><?php echo @number_format($running_total, 2);?></td>
	</tr>
	<tr>
		<td></td>
		<td colspan=2 align=right>+Holiday:</td>
		<td align=right><?php echo @number_format($holiday, 2); $running_total += $holiday;?></td>
	</tr>
	<tr>
		<td></td>
		<td colspan=2 align=right>+PTO Used:</td>
		<td align=right><?php echo @number_format($pto, 2);  $running_total += $pto;?></td>
	</tr>
	<tr>
		<td></td>
		<td colspan=2 align=right>TOTAL HOURS FOR PERIOD:</td>
		<td align=right><?php echo @number_format($running_total, 2);?></td>
	</tr>

</Table>


       <div class="pto">Mileage:<?php echo $mileage?> miles</div>
       <?php 
       
	   ?>
       <div class="signed">SIGNED:_______________________________DATE:______________</div>
<div class="approved">APPROVED BY:_______________________________DATE:______________</div>

</div>
