<A HREF="<?php echo $BASE_DIR; ?>/cv_master/cv_master_main.php">Main</A>
<A HREF="<?php echo $BASE_DIR; ?>/cv_master/cv_master_statement.php">Statement</A>
<A HREF="<?php echo $BASE_DIR; ?>/cv_master/cv_master_configure.php">Configure Inventory</A>
<A HREF="<?php echo $BASE_DIR; ?>/cv_master/cv_master_sales_and_purchases.php">Sales and Purchases</A>
<A HREF="<?php echo $BASE_DIR; ?>/cv_master/cv_master_search_invoices.php">Search Invoices</A>
<A HREF="<?php echo $BASE_DIR; ?>/cv_master/cv_master_export.php">Export Owners</A>



