<?
include("../../../framework/theme.css");
include("invoices_items.css");
framework::navbar();
framework::warning($WARNING);
?>
<script language="JavaScript"

type="text/javascript">
function show_box(obj) {
    var el = document.getElementById(obj);
    if ( el.style.display == 'block' ) {
    el.style.display = 'none';
    }
    else {
    el.style.display = 'block';
    }
}

var xmlHttp;

function createXMLHttpRequest() {
  try {
    xmlHttp = new XMLHttpRequest();
  } catch (trymicrosoft) {
    try {
      xmlHttp = new ActiveXObject("Msxml2.XMLHTTP");
    } catch (othermicrosoft) {
      try {
        xmlHttp = new ActiveXObject("Microsoft.XMLHTTP");
      } catch (failed) {
        xmlHttp = false;
      }
    }
  }

  if (!xmlHttp)
    alert("Error initializing XMLHttpRequest!");
}


function form_extender(formElement, target_container) {
    createXMLHttpRequest();
    form_Name = formElement.getAttribute("name");
    var queryString = "ACTION="+form_Name;
    form_Value = formElement.value;
    queryString += "&VALUE="+form_Value;
    xmlHttp.open("POST", "invoices_create_request.php", true);
    xmlHttp.onreadystatechange = handleStateChange;
    xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");    
    xmlHttp.send(queryString);
    var div = document.getElementById(target_container);
    div.innerHTML =  '';
}

function handleStateChange() {
     if (xmlHttp.readyState == 4) {
       if (xmlHttp.status == 200)
       {
            var xmlDoc = xmlHttp.responseXML;
            if(xmlDoc.getElementsByTagName("removerow").length > 0)
            {
                for(var i = 0; i < xmlDoc.getElementsByTagName("removerow").length; i++)
                {
                    var rowname = xmlDoc.getElementsByTagName("removerow")[i].childNodes[0].nodeValue;
                    thisrow = document.getElementById(rowname);
                    if(thisrow != null)
                    {
                        while(thisrow.hasChildNodes())
                        {
                            thisrow.removeChild(thisrow.lastChild)
                        }
                        thisrow.parentNode.removeChild(thisrow);
                    }
                }
            }
            if(xmlDoc.getElementsByTagName("addrow").length > 0)
            {
                for(var i = 0; i < xmlDoc.getElementsByTagName("addrow").length; i++)
                {
                    add_current_row = xmlDoc.getElementsByTagName("addrow")[i];
                    var rowname = add_current_row.getElementsByTagName("rowname")[0].childNodes[0].nodeValue;
                    var rowformname = add_current_row.getElementsByTagName("rowformname")[0].childNodes[0].nodeValue;
                    var previousrow = add_current_row.getElementsByTagName("previousrow")[0].childNodes[0].nodeValue;
                    var label = add_current_row.getElementsByTagName("label")[0].childNodes[0].nodeValue;
                    var multiple = false;
                    thisrow = document.getElementById(previousrow);
                    newdiv = document.createElement("div");
                    newdiv.setAttribute("id", rowname);
                    newdiv.setAttribute("class", "row");
                    newspan = document.createElement("span");
                    newspan.innerHTML = label;
                    newspan.setAttribute("class", "label");
                    newdiv.appendChild(newspan);
                    newspan = document.createElement("span");
                    newspan.setAttribute("class", "form");
                    
                    newSelect = document.createElement("select");
                    if (add_current_row.getElementsByTagName("multiple")[0])
                    {
                        var multiple = add_current_row.getElementsByTagName("multiple")[0].childNodes[0].nodeValue;
                        newSelect.setAttribute("multiple", true);
                    }
                    newSelect.setAttribute("name", rowformname);
                    newSelect.setAttribute("id", rowformname);
                    newSelect.setAttribute("onchange", "form_extender(this)");
                    for(var j = 0; j < add_current_row.getElementsByTagName("id").length; j++)
                    {
                        newoption  = document.createElement("option");
                        newoption.setAttribute("value", add_current_row.getElementsByTagName("id")[j].childNodes[0].nodeValue);
                        newoption.innerHTML = add_current_row.getElementsByTagName("name")[j].childNodes[0].nodeValue;
                        newSelect.appendChild(newoption);
                    }
                    newspan.appendChild(newSelect);
                    newdiv.appendChild(newspan);
                    thisrow.parentNode.insertBefore(newdiv, thisrow.nextSibling);
                    
                }
            }
       }
       else if (xmlHttp.status == 404)
         alert("Request URL does not exist");
       else
         alert("Error: status code is " + xmlHttp.status);
      }
}

</script>
<div class="portlet2">
    <div class="divheader">Add Items</div>
    <div class="row">
        <span class="label">Customer:</span>
        <span class="formw"><? echo $invoice_info['cv_name']; ?>
        </span>
    </div>    
    <div class="row">
        <span class="label">Recurring:</span>
        <span class="formw"><? echo $invoice_info['frequency']; ?> Days
        </span>
    </div>    
   <div class="row">
        <span class="label">Customer No:</span>
        <span class="formw"><? echo $invoice_info['cv_number']; ?>
        </span>
    </div>    
    <div class="row">
        <span class="label">Sales Account:</span>
        <span class="formw"><? echo $invoice_info['revenueaccount_fullname']; ?>
        </span>
    </div>    
    <div class="row">
        <span class="label">Customer Account:</span>
        <span class="formw"><? echo $invoice_info['customeraccount_fullname']; ?>
        </span>
    </div>    
    <div class="row">
        <span class="bill_col">Bill To
            <div class="row">
                <span class="label">Care Of:</span>
                <span class="formw"><? echo $invoice_info['billto_name']; ?>
                </span>
            </div>    
            <div class="row">
                <span class="label">Address 1:</span>
                <span class="formw"><? echo $invoice_info['billto_address1']; ?>
                </span>
            </div>    
            <div class="row">
                <span class="label">Address 2:</span>
                <span class="formw"><? echo $invoice_info['billto_address2']; ?>
                </span>
            </div>    
            <div class="row">
                <span class="label">City:</span>
                <span class="formw"><? echo $invoice_info['billto_city']; ?>
                </span>
            </div>    
            <div class="row">
                <span class="label">State:</span>
                <span class="formw"><? echo $invoice_info['billto_state']; ?>
                </span>
            </div>    
            <div class="row">
                <span class="label">Zip:</span>
                <span class="formw"><? echo $invoice_info['billto_zip']; ?>
                </span>
            </div>    
        </span>
        <span class="ship_col">Ship To
            <div class="row">
                <span class="label">Care Of:</span>
                <span class="formw"><? echo $invoice_info['shipto_name']; ?>
                </span>
            </div>    
            <div class="row">
                <span class="label">Address 1:</span>
                <span class="formw"><? echo $invoice_info['shipto_address1']; ?>
                </span>
            </div>    
            <div class="row">
                <span class="label">Address 2:</span>
                <span class="formw"><? echo $invoice_info['shipto_address2']; ?>
                </span>
            </div>    
            <div class="row">
                <span class="label">City:</span>
                <span class="formw"><? echo $invoice_info['shipto_city']; ?>
                </span>
            </div>    
            <div class="row">
                <span class="label">State:</span>
                <span class="formw"><? echo $invoice_info['shipto_state']; ?>
                </span>
            </div>    
            <div class="row">
                <span class="label">Zip:</span>
                <span class="formw"><? echo $invoice_info['shipto_zip']; ?>
                </span>
            </div>    
        </span>
    </div>    
    <div class="row">
        <span class="label">Items:</span>
        <span>
        <table>
            <? foreach($invoice_items as $invoice_item)
            {
            ?>
            <form action="<? echo $BASE_DIR ?>/invoices/invoices_recurring_items.php"  method=POST>
            <TR>
                <TD><? echo $invoice_item['inventorytype_name']?></TD>
                <TD><? echo $invoice_item['item_name']?></TD>
                <TD><input type=text name=invoiceitem_price_per size=6 value=<? echo $invoice_item['invoiceitem_price_per']?> > </TD>
                <TD><input type=text name=invoiceitem_count size=5 value=<? echo $invoice_item['invoiceitem_count']?> > </TD>
                <TD><? echo $invoice_item['invoiceitem_price_total']?></TD>
                <TD>
                    <input type="hidden"  name="recurringinvoice_id"  value="<? echo $recurringinvoice_id ?>" >
                    <input type=SUBMIT name="ACTION" value="UPDATE ITEM" >
                    <input type=SUBMIT name="ACTION" value="REMOVE ITEM" >
                    <input type=hidden name="recurringinvoiceitem_id" value=<? echo $invoice_item['recurringinvoiceitem_id']?>>
                </TD>
            </TR>
            </form>
            <?
            }
            ?>
            <TR>
                <TD></TD>
                <TD></TD>
                <TD></TD>
                <TD></TD>
                <TD>$<? echo $invoice_info['invoice_total']?></TD>
                <TD>TOTAL
                </TD>
            </TR>
        </table>
       </span>
    </div>    
    <form action="<? echo $BASE_DIR ?>/invoices/invoices_recurring_items.php"  method=POST>
    <div class="row">
        <span class="label">Item:</span>
        <span class="formw"><select name="add_item">
        <? foreach($items as $row)
        {   
            ?>
            <OPTION VALUE="<? echo $row['inventory_id'] ?>"><? echo $row['item_name'] ?></OPTION>
            <?
        }
        ?>
        </select>
        </span>
    </div>    
    <div class="row">
        <input type="hidden"  name="recurringinvoice_id"  value="<? echo $recurringinvoice_id ?>" >
        <input type="SUBMIT"  name="ACTION"  value="Add Item" >
        <input type="SUBMIT"  name="ACTION"  value="DELETE INVOICE" >
    </div>    
    </form>
</div>
