        <div style="position: static; height: 85mm; width: 270mm">

        <div class="block1">
        <p class="coname"><? echo $SYS_INFO['COMPANY_NAME'] ?></p>
        <p class="coaddy"><? echo $SYS_INFO['COMPANY_MAILADDRESS1'] ?></p>
        <p class="coaddy2"><? echo $SYS_INFO['COMPANY_MAILADDRESS2'] ?></p>
        <p class="cophone"><? echo $SYS_INFO['COMPANY_PHONE'] ?></p>
        <p class="maildate"><? echo $po_info['po_date'] ?></p>
        </div>
        <?
    
        if($po_info['cv_default_city'] != ""){$po_info['cv_default_city'] .= ",";}
        ?>
        <div class="block3">
        <p class="mailaddress1"><? echo $po_info['cv_name'] ?></p>
        <? if($po_info['cv_default_careof'] != "")
        {
            ?><p class="mailaddress1"><? echo $po_info['cv_default_careof'] ?></p><?
        }
        ?>
        <p class="mailaddress2"><? echo $po_info['cv_default_address'] ?></p>
        <p class="mailaddress3"><? echo $po_info['cv_default_city']." ".$po_info['cv_default_state']." ".$po_info['cv_default_zip'] ?></p>
        </div>
        <div class="block5">PO No.<? echo $po_info['po_id'] ?> </div>
        <div class="block4">PURCHASE</div>
    </div>
<?php if($pr_info['purchase_description'] != "" )
{ 
?><table>
      <tr>
                   <TD class="lefttop_left" colspan=2>DESCRIPTION </TD>
    <tr>
         <TD class="endcolumnbottom" rowspan=2 colspan=2 ><? echo $pr_info['purchase_description'] ?></TD>
     </tr>
 </table>
 
<?php
}
?>
    <table>
    	<colgroup>
    	<col class="col1"/>
     	<col class="col2"/>
     	<col class="col3"/>
     	<col class="col4"/>
     	<col class="col5"/>
     	</colgroup>
     	<tr>
    	        <TD class="lefttop">Description</TD>
    	        <TD class="lefttop">Unit Price</TD>
    	        <TD class="lefttop">Quantity</TD>
    	        <TD class="endcolumntop">Amount</TD>
    	</tr>
    <?php foreach($invoice_items as $invoice_item)
    {?>
    	<tr>
    	        <TD class="left"><? echo $invoice_item['inventorytype_name']?>-<? echo $invoice_item['item_name']?></TD>
                <TD class="left" align=right><? echo "$".$invoice_item['purchaseitem_price_per']?> </TD>
                <TD class="left" align=right><? echo $invoice_item['purchaseitem_count']?> </TD>
                <TD class="endcolumn" align=right><? echo "$".$invoice_item['purchaseitem_price_total']?></TD>
    
    	</tr>
    <?php 
    }?>
     	<tr>
    	        <TD class="leftbottom">&nbsp;</TD>
    	        <TD class="leftbottom">&nbsp;</TD>
    	        <TD class="leftbottom">&nbsp;</TD>
    	        <TD class="endcolumnbottom">&nbsp;</TD>
    	</tr>
     	<tr>
    	        <TD ></TD>
    	        <TD ></TD>
 
	        <TD class="endcolumnbottom_right" >Subtotal</TD>
            <TD class="endcolumnbottom" align=right><? echo "$".number_format($po_info['po_total'], 2) ?></TD>
		</tr>
     	<tr>
    	        <TD></TD>
    	        <TD></TD>
 
	        <TD class="endcolumnbottom_right" >Tax</TD>
            <TD class="endcolumnbottom" align=right><? echo "$".number_format($po_info['po_tax'], 2) ?></TD>
		</tr>
     	<tr>
    	        <TD></TD>
    	        <TD></TD>
 
	        <TD class="endcolumnbottom_right">Amount Paid</TD>
            <TD class="endcolumnbottom" align=right><? echo "$".number_format($po_info['total_disbursed'], 2) ?></TD>
		</tr>
     	<tr>
    	        <TD></TD>
    	        <TD></TD>
 
	        <TD class="endcolumnbottom_right">Balance Due</TD>
            <TD class="endcolumnbottom" align=right><? echo "$".number_format($po_info['po_total']-$po_info['total_disbursed'], 2) ?></TD>
		</tr>
    </table>