<?
include("../../../framework/theme.css");
include("available.css");
?>
<div class="portlet">
    <div class="divheader" ALIGN="center" COLSPAN="3" >Property Info</div>
    <div class="row">
        <span class="label">Date Avail:</span>
        <span class="formw"><? echo $dateavail ?></span>
    </div>    
    <div class="row">
        <span class="label">Address:</span>
        <span class="formw"><? echo $address; ?></span>
    </div>    
    <div class="row">
        <span class="label">Apt. #:</span>
        <span class="formw"><? echo $aptnum; ?></span>
    </div>    
    <div class="row">
        <span class="label">City:</span>
        <span class="formw"><? echo $city; ?></span>
    </div>    
    <div class="row">
        <span class="label">State:</span>
        <span class="formw"><? echo $state; ?></span>
    </div>    
    <div class="row">
        <span class="label">Zip:</span>
        <span class="formw"><? echo $zip; ?></span>
    </div>    
    <div class="row">
        <span class="label">T.G #:</span>
        <span class="formw"><? echo $thomasguidenum; ?></span>
    </div>    
    <div class="row">
        <span class="label">Prop #:</span>
        <span class="formw"><? echo $propnum; ?></span>
    </div>    
    <div class="row">
        <span class="label">Type:</span>
        <span class="formw"><? echo $propertytype_id ?></span>
    </div>    
    <div class="row">
        <span class="label">Complex:</span>
        <span class="formw"><? echo $complex; ?></span>
    </div>    
    <div class="row">
        <span class="label">Area:</span>
        <span class="formw"><? echo $area; ?></span>
    </div>    
    <div class="row">
        <span class="label">Garage #:</span>
        <span class="formw"><? echo $garagenum; ?></span>
    </div>    
    <div class="row">
        <span class="label">Parking #:</span>
        <span class="formw"><? echo $parknum; ?></span>
    </div>    
    <div class="row">
        <span class="label">Mail Box #:</span>
        <span class="formw"><? echo $mailboxnum; ?></span>
    </div>    
    <div class="row">
        <span class="label">Square Ft: </span>
        <span class="formw"><? echo $sqft ?></span>
    </div>    
    <div class="row">
        <span class="label">Year Built:</span>
        <span class="formw"><? echo $yrblt ?></span>
    </div>    
    <div class="row">
        <span class="label"># of Rooms:</span>
        <span class="formw"><? echo $numrm ?></span>
    </div>    
     <div class="row">
        <span class="label">Bedrooms:</span>
        <span class="formw"><? echo $numbed ?></span>
    </div>    
    <div class="row">
        <span class="label">Bathrooms:</span>
        <span class="formw"><? echo $numbath ?></span>
    </div>    
    <div class="row">
        <span class="label">Refridgerator:</span>
        <span class="formw"><? echo $refridge ?></span>
    </div>    
    <div class="row">
        <span class="label">Dishwasher:</span>
        <span class="formw"><? echo $dishwasher ?></span>
    </div>    
    <div class="row">
        <span class="label">Microwave:</span>
        <span class="formw"><? echo $microwave ?></span>
    </div>    
    <div class="row">
        <span class="label">Stove:</span>
        <span class="formw"><? echo $stove ?></span>
    </div>    
    <div class="row">
        <span class="label">Type:</span>
        <span class="formw"><? echo $stovetype ?></span>
    </div>    
    <div class="row">
        <span class="label">Fireplace:</span>
        <span class="formw"><? echo $fireplace ?></span>
    </div>    
    <div class="row">
        <span class="label">Type:</span>
        <span class="formw"><? echo $fireplacetype ?></span>
    </div>    
    <div class="row">
        <span class="label">Heat:</span>
        <span class="formw"><? echo $heat ?></span>
    </div>    
    <div class="row">
        <span class="label">Type:</span>
        <span class="formw"><? echo $heattype ?></span>
    </div>    
    <div class="row">
        <span class="label">Air:</span>
        <span class="formw"><? echo $air ?></span>
    </div>    
    <div class="row">
        <span class="label">W/D:</span>
        <span class="formw"><? echo $washdry ?></span>
    </div>    
    <div class="row">
        <span class="label">Type:</span>
        <span class="formw"><? echo $washdrytype ?></span>
    </div>    
    <div class="row">
        <span class="label">W/D Hookup:</span>
        <span class="formw"><? echo $washdryhook ?></span>
    </div>    
    <div class="row">
        <span class="label">Type:</span>
        <span class="formw"><? echo $washdryhooktype ?></span>
    </div>    
    <div class="row">
        <span class="label">Garage:</span>
        <span class="formw"><? echo $garage ?></span>
    </div>    
    <div class="row">
        <span class="label">Openers:</span>
        <span class="formw"><? echo $openers ?></span>
    </div>    
    <div class="row">
        <span class="label">Pool or Spa:</span>
        <span class="formw"><? echo $poolspa ?></span>
    </div>    
    <div class="row">
        <span class="label">Landscaping:</span>
        <span class="formw"><? echo $landscaping ?></span>
    </div>    
    <div class="row">
        <span class="label">Landscaper:</span>
        <span class="formw"><? echo $landscaper ?></span>
    </div>    
    <div class="row">
        <span class="label">Pets:</span>
        <span class="formw"><? echo $pets ?></span>
    </div>    
    <div class="row">
        <span class="label">Pet Deposit:</span>
        <span class="formw"><? echo $petdeposit ?></span>
    </div>    
    <div class="row">
        <span class="label">Smoking:</span>
        <span class="formw"><? echo $smoking ?></span>
    </div>    
    <div class="row">
        <span class="label">Who Pays Gas:</span>
        <span class="formw"><? echo $whopaygas ?></span>
    </div>    
    <div class="row">
        <span class="label">Electric:</span>
        <span class="formw"><? echo $whopayelec ?></span>
    </div>    
    <div class="row">
        <span class="label">Water/Sewer:</span>
        <span class="formw"><? echo $whopaywater ?></span>
    </div>    
    <div class="row">
        <span class="label">Garbage:</span>
        <span class="formw"><? echo $whopaygarbage ?></span>
    </div>    
    <div class="row">
        <span class="label">Description:</span>
        <span class="formw"><? echo $description ?></span>
    </div>    
    <div class="row">
        <span class="label">Rent:</span>
        <span class="formw"><? echo $rentdesired ?></span>
    </div>    
    <div class="row">
        <span class="label">Lease:</span>
        <span class="formw"><? echo $leasedesired ?></span>
    </div>    
  
</div>