<?
framework::warning($WARNING);
?>
<div style="position: static; height: 80mm;">
    <div class="block1">
        <p class="date">Date:<? echo $checkdate;  ?></p>
        <p class="remit_no">Remit No:<? echo $remit_no;  ?></p>
        <p class="checkname">Received From: <? echo $checkname; ?></p>
        <p class="check_no">Check #:<? echo $check_no; ?></p>
        <p class="checknet">Amount:<? echo $net; ?></p>
        <p class="checkamount"><? echo $receipt_string; ?></p>
        <p class="checkmemo">For:<? echo $memo; ?></p>
        <p class="checkmemo">By:<? echo $USER->GetUserFullName(); ?></p>
        <p class="signed">SIGNED__________________________________</p>
    </div>
</div>

<div style="position: static; height: 80mm;">
    <div class="block1">
        <p class="date">Date:<? echo $checkdate;  ?></p>
        <p class="remit_no">Remit No:<? echo $remit_no;  ?></p>
        <p class="checkname">Received From: <? echo $checkname; ?></p>
        <p class="check_no">Check #:<? echo $check_no; ?></p>
        <p class="checknet">Amount:<? echo $net; ?></p>
        <p class="checkamount"><? echo $receipt_string; ?></p>
        <p class="checkmemo">For:<? echo $memo; ?></p>
        <p class="checkmemo">By:<? echo $USER->GetUserFullName(); ?></p>
        <p class="signed">SIGNED__________________________________</p>
    </div>
</div>
<div style="position: static; height: 80mm;">
    <div class="block1">
        <p class="date">Date:<? echo $checkdate;  ?></p>
        <p class="remit_no">Remit No:<? echo $remit_no;  ?></p>
        <p class="checkname">Received From: <? echo $checkname; ?></p>
        <p class="check_no">Check #:<? echo $check_no; ?></p>
        <p class="checknet">Amount:<? echo $net; ?></p>
        <p class="checkamount"><? echo $receipt_string; ?></p>
        <p class="checkmemo">For:<? echo $memo; ?></p>
        <p class="checkmemo">By:<? echo $USER->GetUserFullName(); ?></p>
        <p class="signed">SIGNED__________________________________</p>
    </div>
</div>


