<A HREF="<?php echo $BASE_DIR; ?>/invoices/invoices_main.php">Main</A>
<A HREF="<?php echo $BASE_DIR; ?>/invoices/invoices_configure.php">Configure</A>
<A HREF="<?php echo $BASE_DIR; ?>/invoices/invoices_view_recurring.php">View Recurring</A>
<A HREF="<?php echo $BASE_DIR; ?>/invoices/invoices_charge_recurring.php">Charge Recurring</A>
<A HREF="<?php echo $BASE_DIR; ?>/invoices/invoices_cash_receipts.php">Cash Receipts</A>
