<div id="col_left">
<h3>Tables</h3><a href="admin_main.php">users</a><br>
<a href="admin_rbac_roles.php">roles</a><br>
<a href="admin_rbac_users_has_roles.php">users has roles</a><br>

<a href="admin_rbac_roles_has_permissions.php">roles permissions</a><br>
<br>
<b>Privileges</b><br>
<a href="admin_rbac_privileges.php">privileges</a><br>
<a href="admin_rbac_privileges_has_actions.php">privileges has actions</a><br>
<a href="admin_rbac_actions.php">actions</a><br>
<br>
<b>Domains</b><br>
<a href="admin_rbac_domains.php">domains</a><br>
<a href="admin_rbac_domains_has_objects.php">domains has objects</a><br>

<a href="admin_rbac_objects.php">objects</a><br>
			</div>