
<A HREF="<?php echo $BASE_DIR; ?>/admin/admin_main.php">Main</A>
<A HREF="<?php echo $BASE_DIR; ?>/admin/admin_modules.php">Modules</A>
<A HREF="<?php echo $BASE_DIR; ?>/admin/admin_system.php">System Config</A>
<A HREF="<?php echo $BASE_DIR; ?>/admin/admin_rbac_control.php">RBAC</A>
<A HREF="<?php echo $BASE_DIR; ?>/admin/admin_user_list.php">User List</A>
<A HREF="<?php echo $BASE_DIR; ?>/admin/admin_about.php">About</A>


