<link rel="stylesheet" type="text/css" href="/css/theme.css.php" media="screen" >
<link rel="stylesheet" type="text/css" href="admin_rbac.css" media="screen" >

<?php
$FRAMEWORK->navbar($MODULE_NAME, $BASE_DIR, $USER);
include("admin_rbac_navbar.phtml");
?>

<form  action="" method="POST">
<div class="portlet">
    <div class="divheader">Privileges</div>
    <div class="data">
    <table border="0" cellpadding="2" cellspacing="2" class="tbl_data">
	<tr >
	   <td>
            </td>
            <td align="left">
            <b><a href="admin_rbac_domains.php?&order_by=name">Name</a></b>
            </td>
            <td align="left">
                <b><a href="admin_rbac_domains.php?&order_by=description">Description</a></b>
            </td>
	</tr>
<?php
$class = "green";
foreach($privileges as $row)
{
    ?>
    <tr  class="<?php echo $class?>">
        <td>
            <INPUT type="radio" name="edit_id" value="<?php echo $row['privilege_id'] ?>">
        </td>
        <td>
            <?php echo $row['name'] ?>
        </td>
        <td>
            <?php echo $row['description'] ?>
        </td>
    </tr>
<?php
    switch ($class)
    {
        case "green":
            $class = "yellow";
            break;
        
        case "yellow":
            $class = "green";
            break;
    }




}
?>
    </table>
    </div>
    <div class="pager">
        <span id="pager_links"></span>
        <span id="pager_info"> Total number of rows:<?php echo $priv_count['count'] ?></span>
    </div>
    <div class="button">
        <INPUT name="ACTION" type="submit" value="View / Edit" >
        <INPUT name="ACTION" type="submit" value="Delete" >
    </div>
</div>
</form>


<form  action="" method="POST">
<div class="portlet">
    <div class="divheader">Add/Edit Privilege</div>
    <div class="data">
    <table border="0" class="tbl_frm">
        <tr >
            <td width="30%" class="lbl">
                    Name<span style="color:red">*</span>
            </td>
            <td>
                    <INPUT name="name" type="text" size="30" class="inp" maxlength="50" alt="Name" value="<?php echo $name ?>">
            </td>
        </tr>
        <tr >
            <td class="lbl">
                    Description
            </td>
            <td>
                    <TEXTAREA name="description" type="textarea" cols="40" rows="10" class="inp" alt="Description" ><?php echo $description ?></TEXTAREA>
            </td>
        </tr>
        <tr >
            <td class="lbl">
                    Objects
            </td>
            <td>
                    <SELECT name="privilege_actions[]" multiple size="8"><span style="color:red">*</span>
                    <?php foreach($actions as $act)
                    {
                        ?><OPTION value="<?php echo $act['action_id'] ?>"><?php echo $act['name'] ?></OPTION><?php   
                    }  
                    ?></SELECT>
                
            </td>
        </tr>
        <tr >
            <td colspan="2" align="center" id="button">
                <INPUT name="ACTION" type="submit" value="<?php echo $ACTION_VALUE ?>">
                <INPUT name="id" type="hidden" value="<?php echo $id?>">
            </td>
        </tr>
    </table>
    </div>
</div>
</FORM>
