<!DOCTYPE html>
<html>
<head>
<title><?php  ?></title>
<link rel="stylesheet" type="text/css" href="/css/theme.css.php" media="screen" >
<link rel="stylesheet" type="text/css" href="admin_rbac.css" media="screen" >
</head>
<body>
<?php
$FRAMEWORK->navbar($MODULE_NAME, $BASE_DIR, $USER);
include("admin_rbac_navbar.phtml");
?>

<form  action="" method="POST">
<div class="portlet">
    <div class="divheader">Permissions</div>
    <div class="data">
    <table border="0" cellpadding="2" cellspacing="2" class="tbl_data">
	<tr >
	   <td>
            </td>
            <td align="left">
                <a href="admin_rbac_domains.php?&order_by=name">Role</a>
            </td>
            <td align="left">
            <b><a href="admin_rbac_domains.php?&order_by=name">Privilege</a></b>
            </td>
            <td align="left">
                <b><a href="admin_rbac_domains.php?&order_by=description">Domain</a></b>
            </td>
            <td align="left">
                <b><a href="admin_rbac_domains.php?&order_by=description">Is Allowed</a></b>
            </td>
            <td align="left">
                <b><a href="admin_rbac_domains.php?&order_by=description">Importance</a></b>
            </td>
	</tr>
<?php
$class = "green";
foreach($permissions as $row)
{
    ?>
    <tr  class="<?php echo $class?>">
        <td>
            <INPUT type="radio" name="edit_id" value="<?php echo $row['id'] ?>">
        </td>
        <td>
            <?php echo $row['role_name'] ?>
        </td>
        <td>
            <?php echo $row['privileges_name'] ?>
        </td>
        <td>
            <?php echo $row['domain_name'] ?>
        </td>
        <td>
            <?php echo $row['is_allowed'] ?>
        </td>
        <td>
            <?php echo $row['importance'] ?>
        </td>
    </tr>
<?php
    switch ($class)
    {
        case "green":
            $class = "yellow";
            break;
        
        case "yellow":
            $class = "green";
            break;
    }




}
?>
    </table>
    </div>
    <div class="button">
        <INPUT name="ACTION" type="submit" value="View / Edit" >
        <INPUT name="ACTION" type="submit" value="Delete" >
    </div>
</div>
</form>


<form  action="" method="POST">
<div class="portlet">
    <div class="divheader">Add Permission</div>
    <div class="data">
    <table border="0" class="tbl_frm">
        <tr >
            <td width="30%" class="lbl">
                    Role
            </td>
            <td>
                    <SELECT name="role" multiple size="8"><span style="color:red">*</span>
                    <?php foreach($roles as $act)
                    {
                        ?><OPTION value="<?php echo $act['role_id'] ?>" 
                        <?php 
                        if($act['role_id'] == $role_id)
                        {
                            echo " SELECTED ";
                        }
                        ?>

                        ><?php echo $act['name'] ?></OPTION><?php   
                    }  
                    ?></SELECT>
                
            </td>
        </tr>
        <tr >
            <td width="30%" class="lbl">
                    Privilege
            </td>
            <td>
                    <SELECT name="privilege" multiple size="8"><span style="color:red">*</span>
                    <?php foreach($privileges as $act)
                    {
                        ?>
                        <OPTION value="<?php echo $act['privilege_id']; ?>" 
                        <?php 
                        if($act['privilege_id'] == $privilege_id)
                        {
                            echo " SELECTED ";
                        }
                        
                        echo ">".$act['name'];
                        if($act['is_singular'] == 1)
                        {
                            ?>
                            (SINGLUAR)    
                            <?php
                        }
                        else{?> (NOT SINGULAR) <?php
                        }
                        ?> 
                        </OPTION><?php   
                    }  
                    ?></SELECT>
                
            </td>
        </tr>
        <tr >
            <td width="30%" class="lbl">
                    Domain
            </td>
            <td>
                    <SELECT name="domain" multiple size="8"><span style="color:red">*</span>
                    <?php foreach($domains as $act)
                    {
                        ?>
                        <OPTION value="<?php echo $act['domain_id'] ?>"
                        <?php 
                        if($act['domain_id'] == $domain_id)
                        {
                            echo " SELECTED ";
                        }
                        ?>

                        ><?php echo $act['name'] ?>
                        <?php if($act['is_singular'] == 1)
                        {
                            ?>
                            (SINGLUAR)    
                            <?php
                        }
                        else{?> (NOT SINGULAR) <?php
                        }
                        ?>
                        </OPTION><?php   
                    }  
                    ?></SELECT>
                
            </td>
        </tr>
        <tr >
            <td class="lbl">
                    Is Allowed
            </td>
            <td>
                <INPUT type="checkbox" name="is_allowed" <?php if($is_allowed == 1){echo "checked " ;}?> value="1">
            </td>
        </tr>
        <tr >
            <td colspan="2" align="center" id="button">
                <INPUT name="ACTION" type="submit" value="<?php echo $ACTION_VALUE ?>">
                <INPUT name="id" type="hidden" value="<?php echo $id?>">
            </td>
        </tr>
    </table>
    </div>
</div>
</FORM>
