<?php
include("../../../framework/theme.css");
include("mailing.css");
$FRAMEWORK->navbar($MODULE_NAME, $BASE_DIR, $USER);
$FRAMEWORK->warning($WARNING);
?>
<script language="JavaScript"

type="text/javascript">

var xmlHttp;

function createXMLHttpRequest() {
  try {
    xmlHttp = new XMLHttpRequest();
  } catch (trymicrosoft) {
    try {
      xmlHttp = new ActiveXObject("Msxml2.XMLHTTP");
    } catch (othermicrosoft) {
      try {
        xmlHttp = new ActiveXObject("Microsoft.XMLHTTP");
      } catch (failed) {
        xmlHttp = false;
      }
    }
  }

  if (!xmlHttp)
    alert("Error initializing XMLHttpRequest!");
}
function load_mailing() {
    createXMLHttpRequest();
    var mailing_edit =  document.getElementById("mailing_edit").value;
    var queryString = "ACTION=load_mailing&VALUE="+mailing_edit;
    xmlHttp.open("POST", "mailing_main_request.php", true);
    xmlHttp.onreadystatechange = handleStateChange2;
    xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");    
    xmlHttp.send(queryString);
}

function handleStateChange2() {
     if (xmlHttp.readyState == 4) {
       if (xmlHttp.status == 200)
       {
            var xmlDoc = xmlHttp.responseText;
            var body = document.getElementById("body");
            body.innerHTML = xmlDoc;
       }
       else if (xmlHttp.status == 404)
         alert("Request URL does not exist");
       else
         alert("Error: status code is " + xmlHttp.status);
      }
}

function form_extender(formElement) {
    createXMLHttpRequest();
    form_Name = formElement.getAttribute("name");
    var queryString = "ACTION="+form_Name;
    form_Value = formElement.value;
    queryString += "&VALUE="+form_Value;
    xmlHttp.open("POST", "mailing_main_request.php", true);
    xmlHttp.onreadystatechange = handleStateChange;
    xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");    
    xmlHttp.send(queryString);
    if(form_Value == "fillin")
    {
        var div = document.getElementById("fillin_container");
        newdiv = document.createElement("div");
        newdiv.setAttribute("class", "row");
        newspan = document.createElement("span");
        newspan.innerHTML = "Name:";
        newspan.setAttribute("class", "label");
        newdiv.appendChild(newspan);
        newspan = document.createElement("span");
        newspan.innerHTML = "<input type=text name=\"name\" value=\"\" rows=\"5\">";
        newspan.setAttribute("class", "formw");      
        newdiv.appendChild(newspan);
        div.appendChild(newdiv);
        newdiv = document.createElement("div");
        newdiv.setAttribute("class", "row");
        newspan = document.createElement("span");
        newspan.innerHTML = "Address:";
        newspan.setAttribute("class", "label");
        newdiv.appendChild(newspan);
        newspan = document.createElement("span");
        newspan.innerHTML = "<input type=text name=\"address\" value=\"\">";
        newspan.setAttribute("class", "formw");      
        newdiv.appendChild(newspan);
        div.appendChild(newdiv);
        newdiv = document.createElement("div");
        newdiv.setAttribute("class", "row");
        newspan = document.createElement("span");
        newspan.innerHTML = "City: State: Zip::";
        newspan.setAttribute("class", "label");
        newdiv.appendChild(newspan);
        newspan = document.createElement("span");
        newspan.innerHTML = "<input type=text name=\"city\" value=\"\" size=\"10\"><input type=text name=\"state\" value=\"\" size=\"5\"><input type=text name=\"zip\" value=\"\" size=\"8\">";
        newspan.setAttribute("class", "formw");      
        newdiv.appendChild(newspan);
        div.appendChild(newdiv);
    }
    else
    {    var div = document.getElementById("fillin_container");
        div.innerHTML =  '';
    }
}

function handleStateChange() {
     if (xmlHttp.readyState == 4) {
       if (xmlHttp.status == 200)
       {
            var xmlDoc = xmlHttp.responseXML;
            if(xmlDoc.getElementsByTagName("removerow").length > 0)
            {
                for(var i = 0; i < xmlDoc.getElementsByTagName("removerow").length; i++)
                {
                    var rowname = xmlDoc.getElementsByTagName("removerow")[i].childNodes[0].nodeValue;
                    thisrow = document.getElementById(rowname);
                    if(thisrow != null)
                    {
                        while(thisrow.hasChildNodes())
                        {
                            thisrow.removeChild(thisrow.lastChild)
                        }
                        thisrow.parentNode.removeChild(thisrow);
                    }
                }
            }
            if(xmlDoc.getElementsByTagName("addrow").length > 0)
            {
                for(var i = 0; i < xmlDoc.getElementsByTagName("addrow").length; i++)
                {
                    add_current_row = xmlDoc.getElementsByTagName("addrow")[i];
                    var rowname = add_current_row.getElementsByTagName("rowname")[0].childNodes[0].nodeValue;
                    var rowformname = add_current_row.getElementsByTagName("rowformname")[0].childNodes[0].nodeValue;
                    var previousrow = add_current_row.getElementsByTagName("previousrow")[0].childNodes[0].nodeValue;
                    var label = add_current_row.getElementsByTagName("label")[0].childNodes[0].nodeValue;
                    var multiple = false;
                    
                    thisrow = document.getElementById(previousrow);
                    newdiv = document.createElement("div");
                    newdiv.setAttribute("id", rowname);
                    newdiv.setAttribute("class", "row");
                    newspan = document.createElement("span");
                    newspan.innerHTML = label;
                    newspan.setAttribute("class", "label");
                    newdiv.appendChild(newspan);
                    newspan = document.createElement("span");
                    newspan.setAttribute("class", "form");
                    
                    newSelect = document.createElement("select");
                    if (add_current_row.getElementsByTagName("multiple")[0])
                    {
                        var multiple = add_current_row.getElementsByTagName("multiple")[0].childNodes[0].nodeValue;
                        newSelect.setAttribute("multiple", true);
                    }
                    newSelect.setAttribute("name", rowformname);
                    newSelect.setAttribute("id", rowformname);
                    newSelect.setAttribute("onchange", "form_extender(this)");
                    for(var j = 0; j < add_current_row.getElementsByTagName("id").length; j++)
                    {
                        newoption  = document.createElement("option");
                        newoption.setAttribute("value", add_current_row.getElementsByTagName("id")[j].childNodes[0].nodeValue);
                        newoption.innerHTML = add_current_row.getElementsByTagName("name")[j].childNodes[0].nodeValue;
                        newSelect.appendChild(newoption);
                    }
                    newspan.appendChild(newSelect);
                    newdiv.appendChild(newspan);
                    thisrow.parentNode.insertBefore(newdiv, thisrow.nextSibling);
                    
                }
            }
       }
       else if (xmlHttp.status == 404)
         alert("Request URL does not exist");
       else
         alert("Error: status code is " + xmlHttp.status);
      }
}


</script>

<div class="portlet">
    <form action="<?php echo $BASE_DIR ?>/mailing/mailing_print.php"  method=POST target="_blank">
    <div class="divheader">Enter Mailing Info</div>
    <div class="row">
        <span class="label">TYPE:</span>
        <span class="formw">
            <SELECT  SIZE="1" NAME="type" >
            <OPTION value="EMAIL">EMail</OPTION>
            <OPTION value="SNAIL">Snail Mail</OPTION>
            </SELECT>
        </span>
    </div>    
    <div class="row" id="target_row">
        <span class="label">TO:</span>
        <span class="formw">
            <SELECT  SIZE="1" NAME="target" onchange="form_extender(this);">
            <OPTION value="null"></OPTION>
            <OPTION value="select_customers">Select Customers</OPTION>
            <OPTION value="all_customers">All Customers</OPTION>
            <OPTION value="tagged">All CV Tagged:</OPTION>
            <OPTION value="fillin">Fill In</OPTION>
            </SELECT>
        </span>
    </div>    
    <div id="fillin_container">

    </div>    

    <div class="row">
        <span class="label">Date(YYYY-MM-DD):</span>
        <span class="formw"><?php
            framework::date_selectors($date_year, $date_month, $date_day, "", "");
        ?></span>
    </div>    
    <div class="row">
        <span class="label">Company Name:</span>
        <span class="formw"><input type=text name="coname" value="<?php echo $SYS_INFO['COMPANY_NAME'] ?>" cols="40" rows="5"></span>
    </div>    
    <div class="row">
        <span class="label">Header:</span>
        <span class="formw">
            <textarea NAME="header" COLS="40" ROWS="5"><?php echo $SYS_INFO['COMPANY_MAILADDRESS1'] ?> &#013<?php echo $SYS_INFO['COMPANY_MAILADDRESS2'] ?>&#013Phone <?php echo $SYS_INFO['COMPANY_PHONE'] ?>    Fax <?php echo $SYS_INFO['COMPANY_FAX'] ?> &#013<?php echo $SYS_INFO['COMPANY_GENERALEMAIL'] ?></textarea>
        </span>
    </div>    
<div class="row">
    <span class="label"><input type="BUTTON"  onclick="load_mailing(this)" value="Load Mailing"></span>
    <span class="formw">
        <SELECT  SIZE="1" NAME="mailing_edit" id="mailing_edit" >
        <?php
        foreach ($mailings as $row)
        {
            ?>
            <OPTION value="<?php echo $row['mailing_id'] ?>"><?php echo $row['mailing_name'] ?></OPTION>
            <?php
        }
        ?>
        </SELECT>
    </span>
</div>    
    <div class="row">
        <span class="label">Body:</span>
        <span class="formw"><TEXTAREA NAME="body" id="body" COLS="80" ROWS="20"></TEXTAREA></span>
    </div>    
    <div class="row">
        <span class="label"><input type="SUBMIT"  name="CREATE"  value="Make Letter" ></span>
    </div>    
    </form>
    <div class="row">
::name::
firstname
lastname
address
aptnum
careof
city 
state 
zip 
date
property_address
property_aptnum 
property_city 
property_state
property_zip 

    </div>    
</div>
