<?php 
require_once("../../../framework/theme.css");
require_once("casesystem.css");
?>
<script language="JavaScript"

type="text/javascript">
var xmlHttp;
var caseid ="<?php echo $caseinfo['case_id'] ?>"

function removeCVTag(tag_id) {
  var myForm = document.createElement("form");
  myForm.method="post" ;
  myForm.action = '<?php echo $_SERVER['PHP_SELF']?>' ;
  var myInput = document.createElement("input") ;
  myInput.setAttribute("name", 'ACTION') ;
  myInput.setAttribute("value", 'Remove CV Tag');
  myForm.appendChild(myInput) ;
  var myInput = document.createElement("input") ;
  myInput.setAttribute("name", 'case_id') ;
  myInput.setAttribute("value", caseid);
  myForm.appendChild(myInput) ;
  var myInput = document.createElement("input") ;
  myInput.setAttribute("name", 'cv_id') ;
  myInput.setAttribute("value", tag_id);
  myForm.appendChild(myInput) ;
  document.body.appendChild(myForm) ;
  myForm.submit() ;
  document.body.removeChild(myForm) ;
}

		
function createXMLHttpRequest() {
  try {
    xmlHttp = new XMLHttpRequest();
  } catch (trymicrosoft) {
    try {
      xmlHttp = new ActiveXObject("Msxml2.XMLHTTP");
    } catch (othermicrosoft) {
      try {
        xmlHttp = new ActiveXObject("Microsoft.XMLHTTP");
      } catch (failed) {
        xmlHttp = false;
      }
    }
  }

  if (!xmlHttp)
    alert("Error initializing XMLHttpRequest!");
}

function add_update(id) {
    createXMLHttpRequest();
    var hiddenCaseSystem = "";
    var caseTitle =  document.getElementById("case_title["+id+"]").value;
    var caseSystem = document.getElementById("casesystem_txt["+id+"]").value;
    var action_needed = document.getElementById("action_needed["+id+"]").value;
    var status_text = document.getElementById("status_text["+id+"]").value;
    if(document.getElementById("hiddencasesystem_txt"))
    {
        hiddenCaseSystem =   document.getElementById("hiddencasesystem_txt").value;
    }
    var whoAssigned =   document.getElementById("whoassigned_id["+id+"]").value;
    var queryString = "ACTION=add_update&case_id=" + id + "&case_title=" + caseTitle + "&casesystem_txt=" + encodeURIComponent(caseSystem)
        + "&status_text=" + encodeURIComponent(status_text) + "&action_needed=" +action_needed
        + "&hiddencasesystem_txt=" + encodeURIComponent(hiddenCaseSystem) + "&whoassigned_id=" +whoAssigned                
    xmlHttp.open("POST", "../casesystem/casesystem_savecase.php", true);
    xmlHttp.onreadystatechange = handleStateChange;
    xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");    
    xmlHttp.send(queryString);
    
}
function getCheckedValue(radioObj) {
	if(!radioObj)
		return "";
	var radioLength = radioObj.length;
	if(radioLength == undefined)
		if(radioObj.checked)
			return radioObj.value;
		else
			return "";
	for(var i = 0; i < radioLength; i++) {
		if(radioObj[i].checked) {
			return radioObj[i].value;
		}
	}
	return "";
}

function set_followup(id) {
    createXMLHttpRequest();
    var hiddenCaseSystem = "";
    var year =  document.getElementById("followup_date_year").value;
    var month =  document.getElementById("followup_date_month").value;
    var day =  document.getElementById("followup_date_day").value;
    var hour =  parseInt(document.getElementById("followup_date_hour").value);
    var minute =  document.getElementById("followup_date_minute").value;
    ampm = getCheckedValue(document.forms['caseForm'].elements['ampm']);
    if(ampm == "pm")
    {
        hour = hour+12;
    }
    time = year+"-"+month+"-"+day+" "+hour+":"+minute+":00";
    var queryString = "ACTION=set_followup&case_id=" + id + "&followup=" + time;                
    xmlHttp.open("POST", "../casesystem/casesystem_savecase.php", true);
    xmlHttp.onreadystatechange = handleStateChange;
    xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");    
    xmlHttp.send(queryString);
    
}
function close_case(id) {
    createXMLHttpRequest();
    var hiddenCaseSystem = "";
    var caseTitle =  document.getElementById("case_title["+id+"]").value;
    var caseSystem = document.getElementById("casesystem_txt["+id+"]").value;
    if(document.getElementById("hiddencasesystem_txt"))
    {
        hiddenCaseSystem =   document.getElementById("hiddencasesystem_txt").value;
    }
    var whoAssigned =   document.getElementById("whoassigned_id["+id+"]").value;
    var queryString = "ACTION=close_case&case_id=" + id + "&case_title=" + caseTitle + "&casesystem_txt=" + encodeURIComponent(caseSystem)
        + "&hiddencasesystem_txt=" + encodeURIComponent(hiddenCaseSystem) + "&whoassigned_id=" +whoAssigned;
                
    xmlHttp.open("POST", "../casesystem/casesystem_savecase.php", true);
    xmlHttp.onreadystatechange = handleStateChange;
    xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");    
    xmlHttp.send(queryString);
    
}
function handleStateChange() {
     if (xmlHttp.readyState == 4) {
       if (xmlHttp.status == 200)
       {
            var xmlDoc = xmlHttp.responseXML;
            if(xmlDoc.getElementsByTagName("transaction").length > 0)
            {
                var transaction_status = xmlDoc.getElementsByTagName("transaction")[0].childNodes[0].nodeValue;
                if(transaction_status == "SAVED")
                { 
                    draw_table();
                }
            }    
            if(xmlDoc.getElementsByTagName("login").length > 0)
            {
                var login_status = xmlDoc.getElementsByTagName("login")[0].childNodes[0].nodeValue;
                if(login_status == "FAILED")
                {
                    
                    loginwindow = window.open('../interface/login_popup.html', 'Login', 'height=100,width=300');
                }
            }
               
       }
       else if (xmlHttp.status == 404)
         alert("Request URL does not exist");
       else
         alert("Error: status code is " + xmlHttp.status);
      }
}
function draw_table() {
         window.location = '<?php echo $_SERVER['SCRIPT_NAME']."?".$_SERVER['QUERY_STRING']?>';
}

</script>


<div class="portlet3">
    <div class="divheader">Case History</div>
    <div class="row">
        <span class="col2">Case Title:</span>
        <span class="col3"><span class="bold"><?php echo $caseinfo['case_title'] ?></span></span>
    </div>    
    <div class="row">
        <span class="col2">CV Tags:</span>
        <span class="col3">
<?php
            foreach($case_tags as $row)
            {
                ?>
                   <div class="leadtag"><?php echo $row['cv_name']; ?>|<span onclick="removeCVTag(<?php echo $row['cv_id']; ?>)"> X&nbsp;</span></div>
                <?php
            }
?>            
        </span>
    </div>        
<div class="row">
         <form action="<?php echo $BASE_DIR ?>/casesystem/casesystem_update.php"  method=POST>
        <span class="col2">Tag With Customer:</span>
        <span class="col3">
            <SELECT class="smallsans" NAME="customer_id">
            <OPTION VALUE="none"></OPTION>
            <?php
            foreach($customers as $customer)
            {
                ?>
                <OPTION VALUE="<?php echo $customer['cv_id'] ?>"><?php echo $customer['cv_name'] ?></OPTION>
                <?php 
            }
            
            ?>
            </SELECT><input type="SUBMIT"  name="ACTION"  value="Add Tag" >
            <input type="HIDDEN"  name="case_id"  value="<?php echo $caseinfo['case_id'] ?>" >
        </span>
        </form>
    </div>
    <?php
    if(is_array($caseentrys))
    {
        foreach($caseentrys as $row)
        {
            ?>
    <div class="row">
        <span class="col2">
         	<span class="bold">   <?php echo $userArray[$row['user_id']] ?>   </span>
         	<BR /><?php echo $row['caseentry_date'] ?>
         </span>
     
        <span class="col3">
            <span class="shown">
                <?php echo $row['casesystem_txt'] ?><HR></span>
           
        </span>
     <HR />
    </div>
            <?php
        }
    }
    ?>
</div>
<div class="portlet3">
<form name="caseForm" method="post" action="" onsubmit="return false;">

    <div class="divheader">Update Case</div>
    <div class="row">
        <span class="label">Case Title:</span>
        <span class="bold"><INPUT type=TEXT name="case_title" id="case_title[<?php echo $caseinfo['case_id'] ?>]" value="<?php echo $caseinfo['case_title'] ?>"></span>
    </div>    
    <div class="row">
        <span class="label">Status:</span>
        <span class="formw">
        <SELECT  SIZE="1" NAME="action_needed" id="action_needed[<?php echo $caseinfo['case_id'] ?>]" >
        <OPTION VALUE="0" <?php if($caseinfo['action_needed'] == 0){echo "SELECTED";}?>>NONE</OPTION>
        <OPTION VALUE="1" <?php if($caseinfo['action_needed'] == 1){echo "SELECTED";}?>>Action Needed</OPTION>
        <OPTION VALUE="2" <?php if($caseinfo['action_needed'] == 2){echo "SELECTED";}?>>Waiting Response</OPTION>
        </SELECT>
        </span>
    </div>   
        <div class="row">
            <span class="label">When To Follow Up:</span>
            <span class="formw">
                <?php
                Framework::date_selectors($whenreturn_date_year, $whenreturn_date_month, $whenreturn_date_day, "followup_", "")
                ?>
            <input type="text" name="followup_date_hour" ID="followup_date_hour" size="2" value="<?php echo $whenreturn_date_hour ?>" maxlength="2" />:
            <input type="text" name="followup_date_minute" ID="followup_date_minute" size="2" value="<?php echo $whenreturn_date_minute ?>" maxlength="2" />
            <input type="radio" name="ampm" id="ampm"  value="am" <?php if( date('H', $str_when_return) < 12){ echo " checked";} ?> />am
            <input type="radio" name="ampm" id="ampm" value="pm" <?php if( date('H', $str_when_return) >= 12){ echo " checked";} ?> />pm
            <input type="BUTTON"  name="ACTION"  value="Set Follow Up" onclick="set_followup(<?php echo $caseinfo['case_id'] ?>)">
            </span>
        </div>        <div class="row">
        <span class="label">Next Action/Waiting:</span>
        <span class="bold"><TEXTAREA name="status_text" id="status_text[<?php echo $caseinfo['case_id'] ?>]" rows=3 cols=63 ><?php echo $caseinfo['status_text'] ?></TEXTAREA></span>
    </div>    
    <div class="row">
        <span class="label">Comments:</span>
        <span class="formw"><TEXTAREA name="casesystem_txt" id="casesystem_txt[<?php echo $caseinfo['case_id'] ?>]" rows="10" cols="63"></TEXTAREA></span>
    </div>    

    <div class="row">
        <span class="label">Assign To:</span>
        <span class="formw"><SELECT  SIZE="1" NAME="whoassigned_id" id="whoassigned_id[<?php echo $caseinfo['case_id'] ?>]" >
        <?php foreach($users as $row)
        {	
            ?><OPTION VALUE="<?php echo $row['user_id'] ?>" <?php if($row['user_id'] == $caseinfo['whoassigned_id']){echo " SELECTED";}?> ><?php echo $row['username'] ?></OPTION><?php
        }
        ?>
        </SELECT>
        </span>
    </div>    
    <div class="row">
        <span class="label"><input type="BUTTON"  name="ACTION"  value="Close Case" onclick="close_case(<?php echo $caseinfo['case_id'] ?>)"></span>
        <span class="formw"><input type="BUTTON"  name="ACTION"  value="Add Update" onclick="add_update(<?php echo $caseinfo['case_id'] ?>)">
        </span>
    </div>    
</form>
</div>    
