<?php
include("../../../framework/theme.css");
include("properties_configure.css");
$FRAMEWORK->navbar($MODULE_NAME, $BASE_DIR, $USER);
$FRAMEWORK->warning($WARNING);
?>
<div class="module_container">
    <div class="portlet">
    <form action="<?php echo $BASE_DIR ?>/properties/properties_configure.php"  method=POST>
        <div class="divheader" ALIGN="center" COLSPAN="3" >Create New Property Type</div>
        <div class="row">
            <span class="label">Type:</span>
            <span class="formw">
            <input type="TEXT"  name="propertytype_name"  value="<?php echo $propertytype_name; ?>" size="15">
            </span>
        </div>    
        <div class="row">
            <span class="label">
                <input type="SUBMIT"  name="ACTION"  value="Edit Property Type">
            </span>
            <span class="formw">
                <SELECT  SIZE="1" NAME="properties_type_edit" >
                <?php
                foreach ($propertyTypes as $row)
                {
                    ?>
                    <OPTION value="<?php echo $row['propertytype_id'] ?>"> <?php echo $row['propertytype_name'] ?></OPTION>
                    <?php
                }	
                ?>
                </SELECT>
            </span>
        </div>    
        <div class="row">
            <span class="label">
                <input type="HIDDEN"  name="propertytype_id"  value="<?php echo $propertytype_id; ?>" size="15">
                <input type="SUBMIT"  name="ACTION"  value="Save Property Type" size="15">
            </span>
        </div>    
    </form>
    </div>
</div>