<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<title><?php echo $address ?></title>
<?php 
include("../../../framework/theme.css");
include("properties_edit.css");
$FRAMEWORK->navbar($MODULE_NAME, $BASE_DIR, $USER);
$FRAMEWORK->warning($WARNING);
?>
<script language="JavaScript"

type="text/javascript">

var xmlHttp;

function createXMLHttpRequest() {
  try {
    xmlHttp = new XMLHttpRequest();
  } catch (trymicrosoft) {
    try {
      xmlHttp = new ActiveXObject("Msxml2.XMLHTTP");
    } catch (othermicrosoft) {
      try {
        xmlHttp = new ActiveXObject("Microsoft.XMLHTTP");
      } catch (failed) {
        xmlHttp = false;
      }
    }
  }

  if (!xmlHttp)
    alert("Error initializing XMLHttpRequest!");
}


function form_extender(formElement) {
    createXMLHttpRequest();
    form_Name = formElement.getAttribute("name");
    var queryString = "ACTION="+form_Name;
    form_Value = formElement.value;
    queryString += "&VALUE="+form_Value;
    xmlHttp.open("POST", "vendor_config_request.php", true);
    xmlHttp.onreadystatechange = handleStateChange;
    xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");    
    xmlHttp.send(queryString);
    if(form_Value == "fillin")
    {
        var div = document.getElementById("fillin_container");
        newdiv = document.createElement("div");
        newdiv.setAttribute("class", "row");
        newspan = document.createElement("span");
        newspan.innerHTML = "Name:";
        newspan.setAttribute("class", "label");
        newdiv.appendChild(newspan);
        newspan = document.createElement("span");
        newspan.innerHTML = "<input type=text name=\"name\" value=\"\" rows=\"5\">";
        newspan.setAttribute("class", "formw");      
        newdiv.appendChild(newspan);
        div.appendChild(newdiv);
        newdiv = document.createElement("div");
        newdiv.setAttribute("class", "row");
        newspan = document.createElement("span");
        newspan.innerHTML = "Address:";
        newspan.setAttribute("class", "label");
        newdiv.appendChild(newspan);
        newspan = document.createElement("span");
        newspan.innerHTML = "<input type=text name=\"address\" value=\"\">";
        newspan.setAttribute("class", "formw");      
        newdiv.appendChild(newspan);
        div.appendChild(newdiv);
        newdiv = document.createElement("div");
        newdiv.setAttribute("class", "row");
        newspan = document.createElement("span");
        newspan.innerHTML = "City: State: Zip::";
        newspan.setAttribute("class", "label");
        newdiv.appendChild(newspan);
        newspan = document.createElement("span");
        newspan.innerHTML = "<input type=text name=\"city\" value=\"\" size=\"10\"><input type=text name=\"state\" value=\"\" size=\"5\"><input type=text name=\"zip\" value=\"\" size=\"8\">";
        newspan.setAttribute("class", "formw");      
        newdiv.appendChild(newspan);
        div.appendChild(newdiv);
    }
    else
    {    var div = document.getElementById("fillin_container");
        div.innerHTML =  '';
    }
}

function handleStateChange() {
     if (xmlHttp.readyState == 4) {
       if (xmlHttp.status == 200)
       {
            var xmlDoc = xmlHttp.responseXML;
            if(xmlDoc.getElementsByTagName("removerow").length > 0)
            {
                for(var i = 0; i < xmlDoc.getElementsByTagName("removerow").length; i++)
                {
                    var rowname = xmlDoc.getElementsByTagName("removerow")[i].childNodes[0].nodeValue;
                    thisrow = document.getElementById(rowname);
                    if(thisrow != null)
                    {
                        while(thisrow.hasChildNodes())
                        {
                            thisrow.removeChild(thisrow.lastChild)
                        }
                        thisrow.parentNode.removeChild(thisrow);
                    }
                }
            }
            if(xmlDoc.getElementsByTagName("addrow").length > 0)
            {
                for(var i = 0; i < xmlDoc.getElementsByTagName("addrow").length; i++)
                {
                    add_current_row = xmlDoc.getElementsByTagName("addrow")[i];
                    var rowname = add_current_row.getElementsByTagName("rowname")[0].childNodes[0].nodeValue;
                    var rowformname = add_current_row.getElementsByTagName("rowformname")[0].childNodes[0].nodeValue;
                    var previousrow = add_current_row.getElementsByTagName("previousrow")[0].childNodes[0].nodeValue;
                    var label = add_current_row.getElementsByTagName("label")[0].childNodes[0].nodeValue;
                    var multiple = false;
                    
                    thisrow = document.getElementById(previousrow);
                    newdiv = document.createElement("div");
                    newdiv.setAttribute("id", rowname);
                    newdiv.setAttribute("class", "row");
                    newspan = document.createElement("span");
                    newspan.innerHTML = label;
                    newspan.setAttribute("class", "label");
                    newdiv.appendChild(newspan);
                    newspan = document.createElement("span");
                    newspan.setAttribute("class", "form");
                    
                    newSelect = document.createElement("select");
                    if (add_current_row.getElementsByTagName("multiple")[0])
                    {
                        var multiple = add_current_row.getElementsByTagName("multiple")[0].childNodes[0].nodeValue;
                        newSelect.setAttribute("multiple", true);
                    }
                    newSelect.setAttribute("name", rowformname);
                    newSelect.setAttribute("id", rowformname);
                    newSelect.setAttribute("onchange", "form_extender(this)");
                    for(var j = 0; j < add_current_row.getElementsByTagName("id").length; j++)
                    {
                        newoption  = document.createElement("option");
                        newoption.setAttribute("value", add_current_row.getElementsByTagName("id")[j].childNodes[0].nodeValue);
                        newoption.innerHTML = add_current_row.getElementsByTagName("name")[j].childNodes[0].nodeValue;
                        newSelect.appendChild(newoption);
                    }
                    newspan.appendChild(newSelect);
                    newdiv.appendChild(newspan);
                    thisrow.parentNode.insertBefore(newdiv, thisrow.nextSibling);
                    
                }
            }
       }
       else if (xmlHttp.status == 404)
         alert("Request URL does not exist");
       else
         alert("Error: status code is " + xmlHttp.status);
      }
}


</script>
<body>         

<div class="portlet">
	<form action="<?php echo $BASE_DIR ?>/properties/properties_edit.php"  method=POST>
    <div class="divheader">Enter Property Info</div>
    <div class="row">
        <span class="col1">&nbsp;
        <input type="HIDDEN"  name="property_id"  value="<?php echo $property_id ?>" size="15"></span>
        <span class="col1">
        <input type="SUBMIT"  name="ACTION"  value="SAVE">
        </span>
    </div>    
<?php include("properties_infotable.phtml"); ?>
    <div class="row">
        <span class="col1">&nbsp;
        </span>
        <span class="col1">
        </span>
        <span class="col1"><input type="SUBMIT"  name="ACTION"  value="SAVE">
        <input type="HIDDEN"  name="property_id"  value="<?php echo $property_id ?>" size="15">
        </span>
    </div> 
	</form>
    <form action="<?php echo $BASE_DIR ?>/properties/properties_edit.php"  method=POST>
    	<div class="row">
            <span class="col1">
            <input type="HIDDEN"  name="property_id"  value="<?php echo $property_id ?>" size="15"></span>
            <input type="SUBMIT"  name="ACTION"  value="DELETE">
            </span>
        </div> 
    </form>
</div>


<div class="portlet4">
    <div class="divheader">Upload Files</div>
    <form action="properties_edit.php" method="post" enctype="multipart/form-data">
    <div class="row">
        <span class="formw"><input type="file" name="userfile[]" /> </span>
    </div>    
    <div class="row">
        <span class="formw"><input type="file" name="userfile[]" /> </span>
    </div>    
    <div class="row">
        <span class="formw"><input type="file" name="userfile[]" /> </span>
    </div>   
    <div class="row">
        <span class="formw"><input type="file" name="userfile[]" /> </span>
    </div>    
    <div class="row">
        <span class="formw"><input type="file" name="userfile[]" /> </span>
    </div>    
    <div class="row">
        <span class="formw">
            <input type="HIDDEN"  name="property_id"  value="<?php echo $property_id ?>" />
            <input type="submit"  name="ACTION"  value="Upload Files" />
        </span>
    </div>    
    </form>
</div>

<div class="portlet4">
    <div class="divheader">Property Files</div>
<?php

if(is_array($files))
{
    foreach($files as $row)
    {
        ?>
        <div class="float">
        <a href="../interface/download_file.php?file=<?php echo $row['file_id'] ?>&permission=property">
            <img src="../../thumbnails/<?php echo $DB_SETTINGS['dbname']?>/<?php echo $row['file_id'] ?>" alt="<?php echo $row['fileName'] ?>">
        </a>
        <form action="<?php echo $BASE_DIR ?>/properties/properties_edit.php" method="post">
            <textarea name="fileDesc"><?php echo $row['fileDesc'] ?></textarea><BR />
            <input type="HIDDEN"  name="file_id"  value="<?php echo $row['file_id'] ?>" >
            <input type="HIDDEN"  name="property_id"  value="<?php echo $property_id ?>" >
            <input type="SUBMIT"  name="ACTION"  value="Update Description">
            <input type="SUBMIT"  name="ACTION"  value="Delete File">
        </form>
        </div>    
       <?php
    }
}
?>
</div>



