
<div class="portlet">
    <div class="divheader">Property Info</div>
    <div class="row">
        <span class="label">Address:</span>
        <span class="formw"><? echo $prop_info['property_address']; ?></span>
    </div>    
    <div class="row">
        <span class="label">Apt. #:</span>
        <span class="formw"><? echo $prop_info['property_aptnum']; ?></span>
    </div>    
    <div class="row">
        <span class="label">City:</span>
        <span class="formw"><? echo $prop_info['property_city']; ?> </span>
    </div>    
    <div class="row">
        <span class="label">State:</span>
        <span class="formw"><? echo $prop_info['property_state']; ?></span>
    </div>    
    <div class="row">
        <span class="label">Zip:</span>
        <span class="formw"><? echo $prop_info['property_zip']; ?></span>
    </div>    
    <div class="row">
        <span class="label">County:</span>
        <span class="formw"><? echo $prop_info['property_county']; ?></span>
    </div>    
    <div class="row">
        <span class="label">T.G #:</span>
        <span class="formw"><? echo $prop_info['property_thomasguidenum']; ?></span>
    </div>    
    <div class="row">
        <span class="label">Prop #:</span>
        <span class="formw"><? echo $prop_info['property_propnum']; ?></span>
    </div>    
    <div class="row">
        <span class="label">Type:</span>
        <span class="formw"><? echo $prop_info['propertytype_name'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Complex:</span>
        <span class="formw"><? echo $prop_info['property_complex'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Area:</span>
        <span class="formw"><? echo $prop_info['property_area'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Garage:</span>
        <span class="formw"><? echo $prop_info['property_garage'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Openers:</span>
        <span class="formw"><? echo $prop_info['property_openers'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Garage #:</span>
        <span class="formw"><? echo $prop_info['property_garagenum'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Parking #:</span>
        <span class="formw"><? echo $prop_info['property_parknum'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Garage/Park Additional Info:</span>
        <span class="formw"><? echo $prop_info['property_garageinfo'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Mail Box #:</span>
        <span class="formw"><? echo $prop_info['property_mailboxnum'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Square Ft: </span>
        <span class="formw"><? echo $prop_info['property_sqft'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Year Built:</span>
        <span class="formw"><? echo $prop_info['property_yrblt'] ?></span>
    </div>    
    <div class="row">
        <span class="label"># of Rooms:</span>
        <span class="formw"><? echo $prop_info['property_numrm'] ?></span>
    </div>    
     <div class="row">
        <span class="label">Bedrooms:</span>
        <span class="formw"><? echo $prop_info['property_numbed'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Bathrooms:</span>
        <span class="formw"><? echo $prop_info['property_numbath'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Refridgerator:</span>
        <span class="formw"><? echo $prop_info['property_refridge'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Dishwasher:</span>
        <span class="formw"><? echo $prop_info['property_dishwasher'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Microwave:</span>
        <span class="formw"><? echo $prop_info['property_microwave'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Stove:</span>
        <span class="formw"><? echo $prop_info['property_stove'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Fireplace:</span>
        <span class="formw"><? echo $prop_info['property_fireplace'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Heat:</span>
        <span class="formw"><? echo $prop_info['property_heat'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Air:</span>
        <span class="formw"><? echo $prop_info['property_air'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Washer:</span>
        <span class="formw"><? echo $prop_info['property_washer'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Dryer:</span>
        <span class="formw"><? echo $prop_info['property_dryer'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Pool or Spa:</span>
        <span class="formw"><? echo $prop_info['property_poolspa'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Landscaping:</span>
        <span class="formw"><? echo $prop_info['property_landscaping'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Pets:</span>
        <span class="formw"><? echo $prop_info['property_pets'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Pet Deposit:</span>
        <span class="formw"><? echo $prop_info['property_petdeposit'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Pet Additional Info:</span>
        <span class="formw"><? echo $prop_info['property_petdescription'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Smoking:</span>
        <span class="formw"><? echo $prop_info['property_smoking'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Who Pays Gas:</span>
        <span class="formw"><? echo $prop_info['property_whopaygas'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Electric:</span>
        <span class="formw"><? echo $prop_info['property_whopayelec'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Water/Sewer:</span>
        <span class="formw"><? echo $prop_info['property_whopaywater'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Garbage:</span>
        <span class="formw"><? echo $prop_info['property_whopaygarbage'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Comments:</span>
        <span class="formw"><? echo $prop_info['property_comments'] ?>
        </span>
    </div>
    <div class="row">
        <span class="label">Description:</span>
        <span class="formw"><? echo $prop_info['property_description'] ?>
        </span>
    </div>
    <div class="row">
        <span class="label">Rent Desired:</span>
        <span class="formw"><? echo $prop_info['property_rentdesired'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Rent Minimum:</span>
        <span class="formw"><? echo $prop_info['property_rentmin'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Lease Desired:</span>
        <span class="formw"><? echo $prop_info['property_leasedesired'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Lease Minimum:</span>
        <span class="formw"><? echo $prop_info['property_leasemin'] ?></span>
    </div>    
    
    <div class="row">
        <span class="label">Management Rate:</span>
        <span class="formw"><? echo $prop_info['property_feepercent'] ?></span>
    </div>    
    <div class="row">
        <span class="label">Property For Sale?:</span>
        <span class="formw">
            <?
            if ($prop_info['property_sale'] == 'Y')
                {
                    echo "YES";
                }
            if ($prop_info['property_sale'] == 'N')
                {
                    echo "NO";
                }
            ?>
            </span>
    </div>    
    <div class="row">
        <span class="label">Property a Short Term Rental?:</span>
        <span class="formw">
            <?
            if ($prop_info['property_shortterm'] == 'Y')
                {
                    echo "YES";
                }
            if ($prop_info['property_shortterm'] == 'N')
                {
                    echo "NO";
                }
            ?>
           </span>
    </div>
    <div class="row">
        <span class="label">Property Maintenance?:</span>
        <span class="formw">            <?
            if ($prop_info['property_maintenance'] == 'Y')
                {
                    echo "CONTACT US";
                }

            if ($prop_info['property_maintenance'] == 'N')
                {
                    echo "NOT AUTHORIZED; CONTACT OWNER";
                }
            ?></span>
    </div>
    <div class="row">
    </div>
</div>
