<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Process Serve Update</title>
<link rel="stylesheet" type="text/css" href="/css/theme.css.php" media="screen" >
<link rel="stylesheet" type="text/css" href="process_serve_main.css" media="screen" >
</head>
<body>


<?php 
$FRAMEWORK->navbar($MODULE_NAME, $BASE_DIR, $USER);
$FRAMEWORK->warning($WARNING);

?>



<div class="portlet">
<form action="<?php echo $BASE_DIR ?>/process_serve/process_serve_update.php"  method=POST>
    <div class="divheader">SERVE</div>
    <div class="row">
        <span class="label">First Name:</span>
        <span class="formw">
            <input type="TEXT"  ID="firstname" name="firstname"  value="<?php echo $serve_info['firstname']; ?>" >
        </span>
    </div>    
    <div class="row">
        <span class="label">Last Name:</span>
        <span class="formw">
            <input type="TEXT"  ID="lastname" name="lastname"  value="<?php echo $serve_info['lastname']; ?>" >
        </span>
    </div>    
    <div class="row">
        <span class="label">Type:</span>
        <span class="formw"><SELECT  class="smallsans" SIZE="1" NAME="type" >
<?php
            $types = array('UD','SC','FL','TRO','CH','DV');

     
     		foreach($types as $type)
            {
                ?>
                    <OPTION VALUE="<?php echo $type;?>"
                    <?php 
                    if($serve_info['type'] == $type)
                    { 
                        echo " selected";
                    }
                    
                    ?>
                    ><?php echo $type; ?>
                    </OPTION>
                <?php
            }
?>	
        </SELECT></span>
    </div>    
    <div class="row">
        <span class="label">Street Number/Address Number:</span>
        <span class="formw">
            <input type="TEXT"  name="streetnumber" ID="streetnumber"  value="<?php echo $serve_info['streetnumber']; ?>" >
        </span>
    </div>    
        <div class="row">
        <span class="label">Street Name:</span>
        <span class="formw">
            <input type="TEXT"  name="street" ID="street"  value="<?php echo $serve_info['street']; ?>" >
        </span>
    </div>        

    <div class="row">
        <span class="label">City</span>
        <span class="formw">
                <input type="TEXT"  name="city" ID="city" value="<?php echo $serve_info['city']; ?>" >
        </span>
    </div>    
    <div class="row">
        <span class="label">State:</span>
        <span class="formw">
            <input type="TEXT"  name="state" ID="state"  value="<?php echo $serve_info['state']; ?>" >
        </span>
    </div>    
    <div class="row">
        <span class="label">Zip:</span>
        <span class="formw">
            <input type="TEXT"  name="zip" ID="zip"  value="<?php echo $serve_info['zip']; ?>" >  
        </span>
    </div>    
    <div class="row">
            <span class="label">Serve Date/Time:</span>
            <span class="formw">
                <?php
                $FRAMEWORK->date_selectors($serve_date_year, $serve_date_month, $serve_date_day, "serve_", "")
                ?>
            <input type="text" name="serve_date_hour" size="2" value="<?php echo $serve_date_hour ?>" maxlength="2" />:
            <input type="text" name="serve_date_minute" size="2" value="<?php echo $serve_date_minute ?>" maxlength="2" />
            <input type="radio" name="ampm" value="am" <?php if( date('H') < 12){ echo " checked";} ?> />am
            <input type="radio" name="ampm" value="pm" <?php if( date('H') > 12){ echo " checked";} ?> />pm
            </span>
	</div>      
    <div class="row">
        <span class="label">Comments:</span>   
        <span class="formw"><TEXTAREA name="comments" rows="10" cols="60"><?php echo $FRAMEWORK->br2nl($serve_info['comments']); ?></TEXTAREA></span>
    </div>
        <div class="row">
        <span class="label">Is Complete?:</span>   
        <span class="formw"><input type="checkbox" name="complete" value=1 <?php if( $serve_info['complete'] == 1){ echo " checked";} ?> >YES</span>
    </div>
    <div class="row">
        <span class="label">&nbsp</span>
        <span class="formw">
            <input type="HIDDEN"  name="serve_id"  value="<?php echo $serve_info['serve_id'] ?>" >
            <input type="SUBMIT"  name="ACTION" value="Save" >
            <input class="float_right" type="SUBMIT"  name="ACTION" value="Delete" >
        </span>
    </div>    
  
</form>
</div>    

</body>
</html>