<?php
$FRAMEWORK->print_header($HeadX);
// Include the styles
include_once 'includes/js/popups.php';
include_once 'includes/styles.php';
include("../../../framework/theme.css");
$FRAMEWORK->navbar($MODULE_NAME, $BASE_DIR, $USER);



if ( ! empty ( $cat_id ) )
  $monthURL = "month.php?cat_id=$cat_id&amp;";
else
  $monthURL = 'month.php?';
$helper->display_small_month ( $prevmonth, $prevyear, true, true, "prevmonth",
  $monthURL );
$helper->display_small_month ( $nextmonth, $nextyear, true, true, "nextmonth",
  $monthURL );
?>
<div class="title">
<span class="date"><br /><?php
  echo $calendar->date_to_str ( sprintf ( "%04d%02d01", $thisyear, $thismonth ),
    $helper->DATE_FORMAT_MY, false, false );
?></span>
<span class="user"><?php
  if ( $single_user == "N" ) {
    echo "<br />\n";
    echo $USER->GetUserFullName();
  }
  if ( $is_nonuser_admin ) {
    echo "<br />-- " . translate("Admin mode") . " --";
  }
  if ( $is_assistant ) {
    echo "<br />-- " . translate("Assistant mode") . " --";
  }
?></span>
<?php
  if ( $helper->getCategoriesEnabled() == "Y" && (!$user || ($user == $login || $is_assistant ))) {
    echo "<br /><br />\n";
    print_category_menu('month',sprintf ( "%04d%02d01",$thisyear, $thismonth ),$cat_id );
  }
?>
</div>

<table class="main" style="clear:both;" cellspacing="0" cellpadding="0">
<tr>
 <?php if ( $helper->WEEK_START == 0 ) { ?>
  <th><?php etranslate("Sun")?></th>
 <?php } ?>
 <th><?php etranslate("Mon")?></th>
 <th><?php etranslate("Tue")?></th>
 <th><?php etranslate("Wed")?></th>
 <th><?php etranslate("Thu")?></th>
 <th><?php etranslate("Fri")?></th>
 <th><?php etranslate("Sat")?></th>
 <?php if ( $helper->WEEK_START == 1 ) { ?>
  <th><?php etranslate("Sun")?></th>
 <?php } ?>
</tr>
<?php

// We add 2 hours on to the time so that the switch to DST doesn't
// throw us off.  So, all our dates are 2AM for that day.
//$sun = get_sunday_before ( $thisyear, $thismonth, 1 );
if ( $helper->WEEK_START == 1 ) {
  $wkstart = $calendar->get_monday_before ( $thisyear, $thismonth, 1 );
} else {
  $wkstart = $calendar->get_sunday_before ( $thisyear, $thismonth, 1 );
}
// generate values for first day and last day of month
$monthstart = mktime ( 3, 0, 0, $thismonth, 1, $thisyear );
$monthend = mktime ( 3, 0, 0, $thismonth + 1, 0, $thisyear );

// debugging
//echo "<p>sun = " . date ( "D, m-d-Y", $sun ) . "</p>\n";
//echo "<p>monthstart = " . date ( "D, m-d-Y", $monthstart ) . "</p>\n";
//echo "<p>monthend = " . date ( "D, m-d-Y", $monthend ) . "</p>\n";

// NOTE: if you make HTML changes to this table, make the same changes
// to the example table in pref.php.
for ( $i = $wkstart; date ( "Ymd", $i ) <= date ( "Ymd", $monthend );
  $i += ( 24 * 3600 * 7 ) ) {
  print "<tr>\n";
  for ( $j = 0; $j < 7; $j++ ) {
    $date = $i + ( $j * 24 * 3600 );
    if ( date ( "Ymd", $date ) >= date ( "Ymd", $monthstart ) &&
      date ( "Ymd", $date ) <= date ( "Ymd", $monthend ) ) {
      $thiswday = date ( "w", $date );
      $is_weekend = ( $thiswday == 0 || $thiswday == 6 );
      if ( empty ( $WEEKENDBG ) ) {
        $is_weekend = false;
      }
      print "<td";
      $class = "";
      if ( date ( "Ymd", $date  ) == date ( "Ymd", $today ) ) {
        $class = "today";
      }
      if ( $is_weekend ) {
        if ( strlen ( $class ) ) {
          $class .= " ";
        }
        $class .= "weekend";
      }
      if ( strlen ( $class ) )  {
      echo " class=\"$class\"";
      }
      echo ">";
      //echo date ( "D, m-d-Y H:i:s", $date ) . "<br />";
      $helper->print_date_entries ( date ( "Ymd", $date ),
        ( ! empty ( $user ) ) ? $user : $login, false );
      print "</td>\n";
    } else {
      print "<td>&nbsp;</td>\n";
    }
  }
  print "</tr>\n";
}
?></table>
<br />
<?php
 if ( ! empty ( $eventinfo ) ) echo $eventinfo;

 $helper->display_unapproved_events ( ( $is_assistant || $is_nonuser_admin ? $user : $login ) );
?>

<br />
<a title="<?php etranslate("Generate printer-friendly version")?>" 
class="printer" href="month.php?<?php
   if ( $thisyear ) {
    echo "year=$thisyear&amp;month=$thismonth&amp;";
   }
   if ( ! empty ( $user ) ) {
     echo "user=$user&amp;";
   }
   if ( ! empty ( $cat_id ) ) {
     echo "cat_id=$cat_id&amp;";
   }
  ?>friendly=1" target="cal_printer_friendly" 
onmouseover="window.status = '<?php etranslate("Generate printer-friendly version")
  ?>'">[<?php etranslate("Printer Friendly")?>]</a>
<?php
 $helper->print_trailer ();
?>
</body>
</html>
