<?
include("../../../framework/theme.css");
include("yearend_manual.css");
framework::navbar();
?>
<form action="<? echo $BASE_DIR ?>/yearend/yearend_manualprint.php"  method=POST>
<div class="portlet">
    <div class="divheader">1099 - Manual</div>

    <div class="row">
        <span class="label">First Name</span>
        <span class="formw">
            <input type="text" name="firstname">
        </span>
    </div>    
    <div class="row">
        <span class="label">Last Name</span>
        <span class="formw">
            <input type="text" name="lastname">
        </span>
    </div>    
    <div class="row">
        <span class="label">Income</span>
        <span class="formw">
            <input type="text" name="income">
        </span>
    </div>    
   <div class="row">
        <span class="label">Rent</span>
        <span class="formw">
            <input type="text" name="rent">
        </span>
    </div>    
    <div class="row">
        <span class="label">SSN</span>
        <span class="formw">
            <input type="text" name="ssn">
        </span>
    </div>    
    <div class="row">
        <span class="label">Address</span>
        <span class="formw">
            <input type="text"  name="address"  value="">
        </span>
    </div>    
    <div class="row">
        <span class="label">Careof</span>
        <span class="formw">
            <input type="text"  name="careof"  value="">
        </span>
    </div>    
    <div class="row">
        <span class="label">City</span>
        <span class="formw">
            <input type="text"  name="city"  value="">
        </span>
    </div>    

    <div class="row">
        <span class="label">State</span>
        <span class="formw">
            <input type="text"  name="state"  value="">
        </span>
    </div>    
    <div class="row">
        <span class="label">Zip</span>
        <span class="formw">
            <input type="text"  name="zip"  value=""> 
        </span>
    </div>
    <div class="row">
        <span class="label">Account Number</span>
        <span class="formw">
            <input type="text"  name="account"  value=""> 
        </span>
    </div>
    <div class="row">
    <div class="divheader">1099 - Manual - bottom half</div>
    </div>

    <div class="row">
        <span class="label">First Name</span>
        <span class="formw">
            <input type="text" name="firstname2">
        </span>
    </div>    
    <div class="row">
        <span class="label">Last Name</span>
        <span class="formw">
            <input type="text" name="lastname2">
        </span>
    </div>    
    <div class="row">
        <span class="label">Income</span>
        <span class="formw">
            <input type="text" name="income2">
        </span>
    </div>    
    <div class="row">
        <span class="label">Rent</span>
        <span class="formw">
            <input type="text" name="rent2">
        </span>
    </div>    
    <div class="row">
        <span class="label">SSN</span>
        <span class="formw">
            <input type="text" name="ssn2">
        </span>
    </div>    
    <div class="row">
        <span class="label">Address</span>
        <span class="formw">
            <input type="text"  name="address2"  value="">
        </span>
    </div>    
    <div class="row">
        <span class="label">Careof</span>
        <span class="formw">
            <input type="text"  name="careof2"  value="">
        </span>
    </div>    
    <div class="row">
        <span class="label">City</span>
        <span class="formw">
            <input type="text"  name="city2"  value="">
        </span>
    </div>    

    <div class="row">
        <span class="label">State</span>
        <span class="formw">
            <input type="text"  name="state2"  value="">
        </span>
    </div>    
    <div class="row">
        <span class="label">Zip</span>
        <span class="formw">
            <input type="text"  name="zip2"  value=""> 
        </span>
    </div>
    <div class="row">
        <span class="label">Account Number</span>
        <span class="formw">
            <input type="text"  name="account2"  value=""> 
        </span>
    </div>
    <div class="row">
        <span class="label">&nbsp;</span>
        <span class="formw">
            <input type="submit"  name="ACTION"  value="Print"> 
        </span>
    </div>
</div>
</form>
