<div style="position: static; height: 140mm;" >

<p class="payersname"><? echo $SYS_INFO['COMPANY_NAME'] ?></p>
<p class="payersname2">&nbsp;<? echo $SYS_INFO['COMPANY_NAME2'] ?></p>
<p class="payersaddress1"><? echo $SYS_INFO['COMPANY_MAILADDRESS1'] ?></p>
<p class="payersaddress2"><? echo $SYS_INFO['COMPANY_MAILADDRESS2'] ?></p>
<p class="payerstelephone"> <? echo $SYS_INFO['COMPANY_PHONE'] ?></p>
<p class="payersFEDTAXID"><? if($SYS_INFO['COMPANY_EIN'] != "" ){echo $SYS_INFO['COMPANY_EIN'];}else{ echo "nbsp;" ;} ?> </p>

<p class="ssn"><? echo $ssn ?></p>

<p class="rent"><?echo $rent; ?></p>
<p class="income"><?echo $income; ?></p>
<p class="addressname"><? echo $firstname." ".$lastname." ".$careof ?></p>
<p class="address"><? echo $address ?></p>
<p class="address2"><? echo $city.", ".$state." ".$zip ?></p>
<p class="accountnumber"><? echo $account ?></p>
</div>
<div style="page-break-after:always; height: 110mm; position: static; ">

<p class="payersname"><? echo $SYS_INFO['COMPANY_NAME'] ?></p>
<p class="payersname2">&nbsp;<? echo $SYS_INFO['COMPANY_NAME2'] ?></p>
<p class="payersaddress1"><? echo $SYS_INFO['COMPANY_MAILADDRESS1'] ?></p>
<p class="payersaddress2"><? echo $SYS_INFO['COMPANY_MAILADDRESS2'] ?></p>
<p class="payerstelephone"> <? echo $SYS_INFO['COMPANY_PHONE'] ?></p>
<p class="payersFEDTAXID"><? if($SYS_INFO['COMPANY_EIN'] != "" ){echo $SYS_INFO['COMPANY_EIN'];}else{ echo "nbsp;" ;} ?> </p>

<p class="ssn"><? echo $ssn2 ?></p>

<p class="rent"><?echo $rent2; ?></p>
<p class="income"><?echo $income2; ?></p>
<p class="addressname"><? echo $firstname2." ".$lastname2." ".$careof2 ?></p>
<p class="address"><? echo $address2 ?></p>
<p class="address2"><? echo $city2.", ".$state2." ".$zip2 ?></p>
<p class="accountnumber"><? echo $account2 ?></p>
</div>
