<?
include("../../../framework/theme.css");
include("recurring_checks.css");
framework::navbar();
?>
<div class="module_container">
    <table align="center">
        <tr>
            <td ALIGN="center" COLSPAN="6" BGCOLOR="#CCCCCC"><B>Recurring Transactions</B></td>
        </tr>
        <tr>
            <td ALIGN="right" COLSPAN="1" BGCOLOR="#CCCCCC"><B>Type</B></td>
            <td ALIGN="right" COLSPAN="1" BGCOLOR="#CCCCCC"><B>Comment:</B></td>
            <td ALIGN="right" COLSPAN="1" BGCOLOR="#CCCCCC"><B>From Account:</B></td>
            <td ALIGN="right" COLSPAN="1" BGCOLOR="#CCCCCC"><B>To Account:</B></td>
            <td ALIGN="right" COLSPAN="1" BGCOLOR="#CCCCCC"><B>Amount:</B></td>
            <td ALIGN="right" COLSPAN="1" BGCOLOR="#CCCCCC"><B>Check#</B></td>
        </tr>
    <?
    foreach($recurring as $row)
    {
        ?>
            <form action="<? echo $BASE_DIR ?>/recurring/recurring_address.php"  target="_blank" method=POST>
            <tr>
                <td ALIGN="left" COLSPAN="1" BGCOLOR="#CCCCCC">
                <?
                echo $types[$row['recurringtype_id']];            
                ?>
                </td>
            <td ALIGN="left" COLSPAN="1" BGCOLOR="#CCCCCC">
                <? echo $row['recurring_comment']; ?>
            </td>
            <td ALIGN="left" COLSPAN="1" BGCOLOR="#CCCCCC">
                <?
                echo $accountIDtoFullnameArray[$row['recurring_accountW']];
                ?>
                
            </td>
            <td ALIGN="left" COLSPAN="1" BGCOLOR="#CCCCCC">
                <? 
                echo $accountIDtoFullnameArray[$row['recurring_accountD']];
                ?>
            </td>
            <td ALIGN="left" COLSPAN="1" BGCOLOR="#CCCCCC">
                <? echo $row['recurring_amount']; ?>
            </td>
            <td>
                <input type="HIDDEN"  name="recurring_id"  value="<? echo $row['recurring_id']; ?>" >
                <input type="SUBMIT"  name="CONTACT"  value="EDIT" >
            </td>
        </tr>
        </form>
        <?
    }
    ?>
    </table>
</div>
