<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8" />
    <title><?php echo $all_accounts[$working_account] ?></title>
    <link rel="stylesheet" type="text/css" href="/css/theme.css.php" media="screen" >
    <link rel="stylesheet" type="text/css" href="transactions_account.css" media="screen" >
    
    <script language="JavaScript" type="text/javascript">
    var this_account = <?php echo $working_account ?>;
    var SORT_COLUMN_INDEX;
    var RUNNING_TOTAL = <?php echo $RUNNING_TOTAL ?>;
    var WORKING_ACCOUNT = <?php echo $working_account ?>;
    var DEBIT_OR_CREDIT = '<?php echo $debit_or_credit ?>';
    var DC_COUNT = 0;
    var transaction_edit_dc = new Object();
    var balance_amount = new Number(0.00);
    var transaction_id = "NULL";
    var xmlHttp;
    var last_query;
    var redraw_after_done = false;
    var multi_complete = false;
    var multi_trans_stack = new Array();
    function draw_table() {
        window.location = '<?php $_SERVER['PHP_SELF']."?".$_SERVER['QUERY_STRING']; ?>';
    }
    </script>
    <script type="text/javascript" src="transactions_account.js"></script>
</head>
<body>
    <div class="warning_box" id="warning_box" style="visibility:hidden;">
        <div id='subad'>
            <div style='width:max;text-align:right;clear:both;'><a href='javascript:hidetip2();' style='color:red;font-size:10pt;'><b>CLOSE</b>[X]</a>
            </div>
            <div id="warning_box_message">
                <?php echo $WARNING['message']?>
            </div>
        </div>
    </div>
<div class="portlet">
    <div id="toggle_button" class="divheader" >NEW TRANSACTION -- 
    <span  onclick="toggle_vis(this)">SIMPLE</span>--
	<span  onclick="show_editbox()">ADVANCED</span>
	</div>
    <span class="account_title"><?php echo $all_accounts[$working_account] ?></span>
	<div class="new_trans" id="new_trans">
    	<span class=close_box onclick="hide_editbox()">[X]</span>
		<table class="nb">
            <tr> 
                <th>Date</th>
                <th>Check Num</th>
                <th>Comment</th>
                <th>Rec?</th>
                <th>Reconcile Date</th>
            </tr>
            <tr>
                <td>
                    <?php
                    $FRAMEWORK->date_selectors($date_year, $date_month, $date_day, "transaction[", "]");
                    ?>
                </td>
                <td>
                    <input type="TEXT"  name="transaction[transaction_checkno]" id="transaction[transaction_checkno]"  value="<?php echo $transaction_checkno; ?>" size="8">
                </td>
                <td>
                    <input type="TEXT"  id="transaction[transaction_comment]" name="transaction[transaction_comment]"  value="<?php echo $transaction_comment; ?>" size="16">
                </td>
                <td>
                    <input type="TEXT"  id="transaction[transaction_reconcile]" name="transaction[transaction_reconcile]"  value="<?php echo $transaction_reconcile; ?>" size="1">
                </td>
                <td>
                    <?php
                    $FRAMEWORK->date_selectors($empty, $empty, $empty, "transaction[reconcile", "]");
                    ?>
                </td>
                <td>
                    <input type="BUTTON" class="btn" name="ACTION"  value="Record" onclick="save_transaction()">
                </td>
                <td>
                    <input type="BUTTON" class="btn" name="ACTION"  value="Clear" onclick="clear_transaction()">
                </td>
                <td>
                    <input type="BUTTON" class="btn" name="ACTION"  value="Delete" onclick="delete_transaction()">
                </td>
            </tr>
        </table>
        <div class="unbalanced_amount">Unbalanced Amount
            <div id="unbalanced_amount" class="unbalanced_amount"></div>
        </div>
        <div >
            <div class="DEBIT_LABEL">DEBITS</div>
            <div class="CREDIT_LABEL">CREDITS</div>
        </div>
        <div id="debits_credits">
            <div id="debits_column" class="DEBIT_LABEL"></div>
            <div id="credits_column" class="CREDIT_LABEL"></div>
        </div>
        <table class="nb">
            <tr> 
                <th>Account:</th>
                <th>Amount:</th>
            </tr>
            <tr>
    
                <td>
                    <SELECT  class="smallsans" SIZE="50" NAME="transaction[transaction_account]" id="transaction[transaction_account]" >
                    <?php
                    $transactionAccount->build_accountstree_selectoptions($account_array, $working_account);
                    ?>
                    </SELECT>
                </td>
                <td>
                    <input type="TEXT"  id="transaction[transaction_amount]" name="transaction[transaction_amount]"  value="0.00" size="9">
                </td>
                <td>
                 <SELECT class="smallsans"  id="transaction[transaction_dc]"  name="transaction[transaction_dc]">
                <OPTION VALUE="DEBIT">DEBIT</OPTION>
                <OPTION VALUE="CREDIT">CREDIT</OPTION>
                </SELECT>
                </td>
               <td>
                    <input type="BUTTON" class="btn" name="ACTION"  value="Add Debit/Credit" onclick="add_debit_credit()">
                </td>
            </tr>
        </table>
	</div>
    <div class="simple_edit_box" id="simple_edit_box">
        <span class=close_box onclick="hide_simplebox()">[X]</span>
        <table class="nb">
            <tr> 
                <th>Date</th>
                <th>Check Num</th>
                <th>Comment</th>
                <th>Account</th>
                <th>Debit</th>
                <th>Credit</th>
                <th></th>
                <th>Rec?</th>
                <th>Reconcile Date</th>
                
            </tr>
            <tr>
                <td>
                    <?php
                    $FRAMEWORK->date_selectors($date_year, $date_month, $date_day, "transaction_simple[", "]");
                    ?>
                </td>
                <td>
                    <input type="TEXT"  name="transaction_simple[transaction_checkno]" id="transaction_simple[transaction_checkno]"  value="" size="8">
                </td>
                <td>
                    <input type="TEXT"  id="transaction_simple[transaction_comment]" name="transaction_simple[transaction_comment]"  value="" size="16">
                </td>
    
                <td>
                    <SELECT  class="smallsans" SIZE="50" NAME="transaction_simple[transaction_account]" id="transaction_simple[transaction_account]" >
                    <?php
                    $transactionAccount->build_accountstree_selectoptions($account_array, '');
                    ?>
                    </SELECT>
                </td>
                <td>
                    <input type="TEXT"  id="transaction_simple[transaction_debit]" name="transaction_simple[transaction_debit]" onchange="set_credit_null()" value="" size="9">
                </td>
                <td>
                    <input type="TEXT"  id="transaction_simple[transaction_credit]" name="transaction_simple[transaction_credit]" onchange="set_debit_null()" value="" size="9">
                </td>
                <td>
                    <input type="BUTTON" class="btn" name="ACTION"  value="Save" onclick="save_simple_transaction()"><BR/><BR/>
                    <input type="BUTTON" class="btn" name="ACTION"  value="Clear" onclick="clear_transaction()"><BR/><BR/>
                    <input type="BUTTON" id="edit_more_button" class="btn" name="ACTION"  value="Edit More" onclick="open_editbox()"><BR/><BR/>
                    <input type="BUTTON" class="btn" name="ACTION"  value="Delete" onclick="delete_transaction()">
                    <input type="HIDDEN" name="transaction_simple[transaction_id]" id="transaction_simple[transaction_id]"  value="NULL" >
                </td>      
                <td>
                    <input type="TEXT"  id="transaction_simple[transaction_reconcile]" name="transaction_simple[transaction_reconcile]"  value="" size="1">
                </td>
                <td>
                    <?php
                    $FRAMEWORK->date_selectors($empty, $empty, $empty, "transaction_simple[reconcile", "]");
                    ?>
                </td>
           </tr>
        </table>
	</div>
</div>
<div class="portlet2">
    <div class="divheader">Transactions <?php echo $starting_point?> thru <?php echo $starting_point+$rowNumbers;?></div>
    <div class="row" id="rowhead">
            <?php for($i = 0; $i <= $page_count; $i++)
            {
                ?>
                <a href="<?php echo $BASE_DIR ?>/transactions/transactions_account.php?id=<?php echo $working_account ?>&amp;page=<?php echo $i?>"><?php echo $i?></a>
                <?php
            }
            ?>    
        <A href="transactions_account.php?id=<?php echo $working_account ?>&amp;VIEWALL=Y">VIEW ALL</A>
    </div>    
    <form id="transactions_form">
    <table class="fixed" id="unique_id">
        <tr>    
            <td class="nb"></td>
            <td class="nb"></td>
            <td class="nb"><input type=button onclick="move_checked()" value="Move Checked"></td>
            <td class="nb">TO:</td>
            <td>
                <SELECT  class="smallsans" SIZE="1" NAME="multi_move" id="multi_move" >
                <?php
                $transactionAccount->build_accountstree_selectoptions($account_array, '');
                ?>
                </SELECT>
            </td>
            <td class="nb"></td>
            <td class="nb"></td>
            <td class="nb">Check All 
            </td>
			<TD><input type="checkbox" name="checkAll" value="Comfortable with"
   			 onclick="javascript:check_all('transactions_form', this, 'multi_select[]')"  ></TD>
        </tr>
        <tr> 
            <td><a href="#" onclick="ts_resortTable(this);return false;">Date:<span class="sortarrow">&nbsp;&nbsp;&uarr;</span></a></td>
            <td><a href="#" onclick="ts_resortTable(this);return false;">Check<BR/> Num:<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td>
            <td><a href="#" onclick="ts_resortTable(this);return false;">Comment:<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td>
            <td><a href="#" onclick="ts_resortTable(this);return false;">R:<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td>
            <td><a href="#" onclick="ts_resortTable(this);return false;">Account:<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td>
            <td><a href="#" onclick="ts_resortTable(this);return false;">Debit:<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td>
            <td><a href="#" onclick="ts_resortTable(this);return false;">Credit:<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td>
            <td><a href="#" onclick="ts_resortTable(this);return false;">Running<BR />Balance:<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td>
        </tr>
        <tr> 
            <td class="nb"></td>
            <td class="nb"></td>
            <td class="nb"></td>
            <td class="nb"></td>
            <td class="nb"></td>
            <td class="nb"></td>
            <td class="nb"></td>
            <td align="right" class="<?php if ($RUNNING_TOTAL < 0){
                echo "negnb";
            }else {echo "blacknb";} 
            ?>"><?php echo $RUNNING_TOTAL ?></td>
        </tr>
    
<?php
if(is_array($transactions))
{	
$class = "green";

    foreach($transactions as $row)
    {
        ?>
        <tr class="<?php echo $class?>"  id="<?php echo  $row['transaction_id'] ?>" onclick="open_simplebox(<?php echo  $row['transaction_id'] ?>)">
            <td>
                <?php echo $row['transaction_date'] ?>
            </td>
            <td class="right">
                <?php echo $row['transaction_checkno']; ?>
            </td>
            <td  class="left">
                <?php echo $row['transaction_comment']; ?>
            </td>
            <td>
                <?php echo $row['transaction_reconcile']; ?>
            </td>
            <td class="left">
                <?php  if(strpos($row['split'], ','))
                    {
                        echo "SPLIT";
                    }
                    else
                    {
                        echo (@$all_accounts[$row['split']] ? $all_accounts[$row['split']] : "NOT SET - No account for transaction"); ; 
                    }
                    ?>
            </td>
            <td class="right">
            <?php  if($row['transaction_dc']== 'DEBIT')
            {
                  echo $row['transaction_dc_amount']; 
            }
            ?>
            </td>
            <td class="right">
            <?php  if($row['transaction_dc']== 'CREDIT')
            {
                  echo $row['transaction_dc_amount']; 
            }
            ?>
            </td>
            <?php
            if($row['transaction_dc']== 'DEBIT')
            {
                if($debit_or_credit == 'DEBIT')
                {
                    $RUNNING_TOTAL = bcadd($RUNNING_TOTAL, $row['transaction_dc_amount'], 2);

                }
                else
                {
                    $RUNNING_TOTAL = bcsub($RUNNING_TOTAL, $row['transaction_dc_amount'], 2);
                }
            }
            if($row['transaction_dc']== 'CREDIT')
            {
                if($debit_or_credit == 'DEBIT')
                {
                    $RUNNING_TOTAL = bcsub($RUNNING_TOTAL, $row['transaction_dc_amount'], 2);

                }
                else
                {
                    $RUNNING_TOTAL = bcadd($RUNNING_TOTAL, $row['transaction_dc_amount'], 2);
                }
            }
            ?>
            <td align="right" class="<?php


            if ($RUNNING_TOTAL < 0)
            {
                echo "neg";
            }
            else{
                echo "black";
            } 
            ?>"><?php echo $RUNNING_TOTAL; ?>
            </td>
            <td class="right">
                <input type="checkbox"  name="multi_select[]" id="multi_select[]" onclick="doSomething(this,event)" value="<?php echo $row["transaction_id"]; ?>">
            </td>
        </tr>    
        <?php
        switch ($class)
        {
            case "green":
                $class = "yellow";
                break;
            
            case "yellow":
                $class = "green";
                break;
        }
    }
}
?>
        <tr>    
            <td class="nb"></td>
            <td class="nb"></td>
            <td class="nb"></td>
            <td class="nb"></td>
            <td class="nb"></td>
            <td class="nb"></td>
            <td class="nb" align=right>
                BALANCE:
            </td>
            <td id="print_total" align="right" class="<?php if ($TOTAL < 0){
                    echo "negnb";
                }else {echo "blacknb";} 
                ?> 
            "><?php echo $TOTAL ?>
            </td>
        </tr>
        <tr>    
            <td class="nb"></td>
            <td class="nb"></td>
            <td class="nb"><input type=button onclick="delete_checked()" value="Delete Checked"></td>
            <td class="nb"></td>
            <td class="nb"></td>
            <td class="nb"></td>
            <td class="nb"></td>
            <td class="nb">Check All 
            </td>
			<TD><input type="checkbox" name="checkAll" value="Comfortable with"
    		onclick="javascript:check_all('transactions_form', this, 'multi_select[]')"  ></TD>
        </tr>
    </table>
    </form>
</div>

</body>
</html>